<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Day 2 | Introduction to R 2024</title>
  <meta name="description" content="Workshop website for the 2024 Introduction to R Canadian Bioinformatics Workshop" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Day 2 | Introduction to R 2024" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://bioinformaticsdotca.github.io/INR_2024/img/bioinformatics_logo.png" />
  <meta property="og:description" content="Workshop website for the 2024 Introduction to R Canadian Bioinformatics Workshop" />
  <meta name="github-repo" content="bioinformaticsdotca/INR_2024" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Day 2 | Introduction to R 2024" />
  
  <meta name="twitter:description" content="Workshop website for the 2024 Introduction to R Canadian Bioinformatics Workshop" />
  <meta name="twitter:image" content="https://bioinformaticsdotca.github.io/INR_2024/img/bioinformatics_logo.png" />

<meta name="author" content="Faculty: Frances Wong, Andrés Melani, Amin Noorani, Zoe Klein, Michelle Brazas, and Nia Hughes" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
<link rel="prev" href="day-1.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<a href="https://bioinformaticsdotca.github.io/">
 <img src="img/bioinformatics_logo.png" width="90%" alt="bioinformatics.ca logo" style="display:block; margin-left:auto; margin-right:auto; margin-top:15px;">
 </a>
 <li><center><strong><a href="./"><br>Introduction to R<br><br></a></strong></center></li>
 <a href="./">
 <img src="img/CBW_introtoR-icon.png" width="70%" alt="Introduction to R logo" style="display:block; margin-left:auto; margin-right:auto; ">
 </a>
 <br>

<li class="divider"></li>
<li class="part"><span><b>I Introduction</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Workshop Info</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#pre-work"><i class="fa fa-check"></i>Pre-work</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="meet-your-faculty.html"><a href="meet-your-faculty.html"><i class="fa fa-check"></i>Meet Your Faculty</a></li>
<li class="chapter" data-level="" data-path="data-setup.html"><a href="data-setup.html"><i class="fa fa-check"></i>Data Setup</a></li>
<li class="part"><span><b>II Modules</b></span></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html"><i class="fa fa-check"></i>Day 1</a>
<ul>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#lecture"><i class="fa fa-check"></i>Lecture</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#lab"><i class="fa fa-check"></i>Lab</a>
<ul>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#introduction-to-r"><i class="fa fa-check"></i>Introduction to R</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#general-syntax"><i class="fa fa-check"></i>General Syntax</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#getting-started-with-data"><i class="fa fa-check"></i>Getting Started with Data</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#importing-data"><i class="fa fa-check"></i>Importing Data</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#revising-the-r-environment"><i class="fa fa-check"></i>Revising the R Environment</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#installing-packages-from-cran"><i class="fa fa-check"></i>Installing Packages from CRAN</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#data-wrangling"><i class="fa fa-check"></i>Data Wrangling</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#adding-new-columns-of-data"><i class="fa fa-check"></i>Adding New Columns of Data</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#tidyverse"><i class="fa fa-check"></i>Tidyverse</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#plotting-with-base-r"><i class="fa fa-check"></i>Plotting with Base R</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#scatterplot-with-ggplot"><i class="fa fa-check"></i>Scatterplot with ggplot</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#multi-panel-plots-with-ggplot"><i class="fa fa-check"></i>Multi-panel Plots with ggplot</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#exporting-plots"><i class="fa fa-check"></i>Exporting plots</a></li>
<li class="chapter" data-level="" data-path="day-1.html"><a href="day-1.html#day-1-project"><i class="fa fa-check"></i>Day 1 Project</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html"><i class="fa fa-check"></i>Day 2</a>
<ul>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#lab-1"><i class="fa fa-check"></i>Lab</a>
<ul>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#project-review"><i class="fa fa-check"></i>Project Review</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#review-with-datasaurus-dozen"><i class="fa fa-check"></i>Review with Datasaurus Dozen</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#generalizable-code"><i class="fa fa-check"></i>Generalizable Code</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#generalizable-plots"><i class="fa fa-check"></i>Generalizable Plots</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#exercise-3"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#dataset---heart-stroke-prediction"><i class="fa fa-check"></i>Dataset - Heart Stroke Prediction</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#exercise-4"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#exercise-5"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#factors"><i class="fa fa-check"></i>Factors</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#incomplete-data"><i class="fa fa-check"></i>Incomplete Data</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#exercise-6"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#loops"><i class="fa fa-check"></i>Loops</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#exercise-7"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#conditional-for-loops"><i class="fa fa-check"></i>Conditional for Loops</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#exercise-8"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#countinous-variables"><i class="fa fa-check"></i>Countinous Variables</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#linear-models"><i class="fa fa-check"></i>Linear Models</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#exercise-9"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#demo-detour-to-function-for-lm-plots"><i class="fa fa-check"></i>Demo Detour to Function for lm Plots</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#notes-on-data-types"><i class="fa fa-check"></i>Notes on Data Types</a></li>
<li class="chapter" data-level="" data-path="day-2.html"><a href="day-2.html#day-2-project"><i class="fa fa-check"></i>Day 2 Project</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<h1 id="sponsors">Sponsors</h1>
<center>
<a href="https://genomecanada.ca/"><img src="img/sponsors/genomecanada.png" height="70" style="display:inline-block;"  style="padding-bottom: 20px" alt="Genome Canada logo.">
<a href="https://www.ontariogenomics.ca/"><img src="img/sponsors/ontariogenomics.png" height="70" style="display:inline-block;" style="padding-bottom: 20px;" alt="Ontario Genomics logo.">
<br><br>
<a href="https://oicr.on.ca/"><img src="img/sponsors/oicr.png" width=25% style="display:inline-block;" style="padding-bottom: 20px" alt="Ontario Institute for Cancer Research logo.">
<a href="https://www.hpcforhealth.ca/"><img src="img/sponsors/hpc4health.png" width=60% style="display:inline-block;" style="padding-bottom: 20px "alt="HPC4Health logo.">
<br><br>
<a href="https://computationalgenomics.ca/"><img src="img/sponsors/Canadian_Centre_for_Computational_Genomics.png" style="display:inline-block;" width=35% style="padding-bottom: 20px" alt="Canadian Centre for Computational Genomcis logo."> <!--- replace the directory with your sponsor logo --->

<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li></center>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R 2024</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="day-2" class="section level1 hasAnchor">
<h1>Day 2<a href="day-2.html#day-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="lab-1" class="section level2 hasAnchor">
<h2>Lab<a href="day-2.html#lab-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="project-review" class="section level3 hasAnchor">
<h3>Project Review<a href="day-2.html#project-review" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this mini guided project, we will be working with a dataset quantifying water quality that is publicly available at: <a href="https://www.kaggle.com/datasets/adityakadiwal/water-potability?resource=download" class="uri">https://www.kaggle.com/datasets/adityakadiwal/water-potability?resource=download</a></p>
<p>Here is some description of the data:</p>
<p>Access to safe drinking-water is essential to health, a basic human right and a component of effective policy for health protection. This is important as a health and development issue at a national, regional and local level. In some regions, it has been shown that investments in water supply and sanitation can yield a net economic benefit, since the reductions in adverse health effects and health care costs outweigh the costs of undertaking the interventions.
Content</p>
<p>The water_potability.csv file contains water quality metrics for 3276 different water bodies. More information about each of the columns can be found in the link above</p>
<p>pH value
Hardness
Solids (Total dissolved solids - TDS)
Chloramines
Sulfate
Conductivity
Organic_carbon
Trihalomethanes
Turbidity
Potability</p>
<p>Insert a code chunk underneath each step to carry out the instruction.</p>
<ol style="list-style-type: decimal">
<li>Read in the “water_potability.csv” data into an object called data Check the object you created by printing out the first 10 rows and applying the summary function.</li>
</ol>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="day-2.html#cb137-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;../INR-2024/datasets/water_potability.csv&quot;</span>)</span>
<span id="cb137-2"><a href="day-2.html#cb137-2" tabindex="-1"></a></span>
<span id="cb137-3"><a href="day-2.html#cb137-3" tabindex="-1"></a><span class="fu">head</span>(data, <span class="at">n=</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>##           ph Hardness   Solids Chloramines  Sulfate Conductivity Organic_carbon
## 1         NA 204.8905 20791.32    7.300212 368.5164     564.3087      10.379783
## 2   3.716080 129.4229 18630.06    6.635246       NA     592.8854      15.180013
## 3   8.099124 224.2363 19909.54    9.275884       NA     418.6062      16.868637
## 4   8.316766 214.3734 22018.42    8.059332 356.8861     363.2665      18.436524
## 5   9.092223 181.1015 17978.99    6.546600 310.1357     398.4108      11.558279
## 6   5.584087 188.3133 28748.69    7.544869 326.6784     280.4679       8.399735
## 7  10.223862 248.0717 28749.72    7.513408 393.6634     283.6516      13.789695
## 8   8.635849 203.3615 13672.09    4.563009 303.3098     474.6076      12.363817
## 9         NA 118.9886 14285.58    7.804174 268.6469     389.3756      12.706049
## 10 11.180284 227.2315 25484.51    9.077200 404.0416     563.8855      17.927806
##    Trihalomethanes Turbidity Potability
## 1         86.99097  2.963135          0
## 2         56.32908  4.500656          0
## 3         66.42009  3.055934          0
## 4        100.34167  4.628771          0
## 5         31.99799  4.075075          0
## 6         54.91786  2.559708          0
## 7         84.60356  2.672989          0
## 8         62.79831  4.401425          0
## 9         53.92885  3.595017          0
## 10        71.97660  4.370562          0</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="day-2.html#cb139-1" tabindex="-1"></a>data[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, ]</span></code></pre></div>
<pre><code>##           ph Hardness   Solids Chloramines  Sulfate Conductivity Organic_carbon
## 1         NA 204.8905 20791.32    7.300212 368.5164     564.3087      10.379783
## 2   3.716080 129.4229 18630.06    6.635246       NA     592.8854      15.180013
## 3   8.099124 224.2363 19909.54    9.275884       NA     418.6062      16.868637
## 4   8.316766 214.3734 22018.42    8.059332 356.8861     363.2665      18.436524
## 5   9.092223 181.1015 17978.99    6.546600 310.1357     398.4108      11.558279
## 6   5.584087 188.3133 28748.69    7.544869 326.6784     280.4679       8.399735
## 7  10.223862 248.0717 28749.72    7.513408 393.6634     283.6516      13.789695
## 8   8.635849 203.3615 13672.09    4.563009 303.3098     474.6076      12.363817
## 9         NA 118.9886 14285.58    7.804174 268.6469     389.3756      12.706049
## 10 11.180284 227.2315 25484.51    9.077200 404.0416     563.8855      17.927806
##    Trihalomethanes Turbidity Potability
## 1         86.99097  2.963135          0
## 2         56.32908  4.500656          0
## 3         66.42009  3.055934          0
## 4        100.34167  4.628771          0
## 5         31.99799  4.075075          0
## 6         54.91786  2.559708          0
## 7         84.60356  2.672989          0
## 8         62.79831  4.401425          0
## 9         53.92885  3.595017          0
## 10        71.97660  4.370562          0</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Notice that the pH column contains a couple hundred NA values. NA are special values in R (like how “pi” is preset to a value of 3.14159…) to indicate that there is missing data, or it is not available. There are also some NAs in the Sulfate and Trihalomethanes columns.</li>
</ol>
<p>Create new object called water_df that only contains complete observations.</p>
<div class="callout-orange">
<span class="callout-icon"><i class="fas fa-fire" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Tip</p>
</div>
<p>Take a look at the function called <code>na.omit()</code>. In most cases, someone’s already done what you’ve wanted to do so there may already be code or functions that you can adapt and use!</p>
</div>
</div>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="day-2.html#cb141-1" tabindex="-1"></a>water_df <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data)</span>
<span id="cb141-2"><a href="day-2.html#cb141-2" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code></pre></div>
<pre><code>##        ph            Hardness          Solids         Chloramines    
##  Min.   : 0.000   Min.   : 47.43   Min.   :  320.9   Min.   : 0.352  
##  1st Qu.: 6.093   1st Qu.:176.85   1st Qu.:15666.7   1st Qu.: 6.127  
##  Median : 7.037   Median :196.97   Median :20927.8   Median : 7.130  
##  Mean   : 7.081   Mean   :196.37   Mean   :22014.1   Mean   : 7.122  
##  3rd Qu.: 8.062   3rd Qu.:216.67   3rd Qu.:27332.8   3rd Qu.: 8.115  
##  Max.   :14.000   Max.   :323.12   Max.   :61227.2   Max.   :13.127  
##  NA&#39;s   :491                                                         
##     Sulfate       Conductivity   Organic_carbon  Trihalomethanes  
##  Min.   :129.0   Min.   :181.5   Min.   : 2.20   Min.   :  0.738  
##  1st Qu.:307.7   1st Qu.:365.7   1st Qu.:12.07   1st Qu.: 55.845  
##  Median :333.1   Median :421.9   Median :14.22   Median : 66.622  
##  Mean   :333.8   Mean   :426.2   Mean   :14.28   Mean   : 66.396  
##  3rd Qu.:360.0   3rd Qu.:481.8   3rd Qu.:16.56   3rd Qu.: 77.337  
##  Max.   :481.0   Max.   :753.3   Max.   :28.30   Max.   :124.000  
##  NA&#39;s   :781                                     NA&#39;s   :162      
##    Turbidity       Potability    
##  Min.   :1.450   Min.   :0.0000  
##  1st Qu.:3.440   1st Qu.:0.0000  
##  Median :3.955   Median :0.0000  
##  Mean   :3.967   Mean   :0.3901  
##  3rd Qu.:4.500   3rd Qu.:1.0000  
##  Max.   :6.739   Max.   :1.0000  
## </code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="day-2.html#cb143-1" tabindex="-1"></a><span class="fu">summary</span>(water_df)</span></code></pre></div>
<pre><code>##        ph             Hardness          Solids         Chloramines    
##  Min.   : 0.2275   Min.   : 73.49   Min.   :  320.9   Min.   : 1.391  
##  1st Qu.: 6.0897   1st Qu.:176.74   1st Qu.:15615.7   1st Qu.: 6.139  
##  Median : 7.0273   Median :197.19   Median :20933.5   Median : 7.144  
##  Mean   : 7.0860   Mean   :195.97   Mean   :21917.4   Mean   : 7.134  
##  3rd Qu.: 8.0530   3rd Qu.:216.44   3rd Qu.:27182.6   3rd Qu.: 8.110  
##  Max.   :14.0000   Max.   :317.34   Max.   :56488.7   Max.   :13.127  
##     Sulfate       Conductivity   Organic_carbon  Trihalomethanes  
##  Min.   :129.0   Min.   :201.6   Min.   : 2.20   Min.   :  8.577  
##  1st Qu.:307.6   1st Qu.:366.7   1st Qu.:12.12   1st Qu.: 55.953  
##  Median :332.2   Median :423.5   Median :14.32   Median : 66.542  
##  Mean   :333.2   Mean   :426.5   Mean   :14.36   Mean   : 66.401  
##  3rd Qu.:359.3   3rd Qu.:482.4   3rd Qu.:16.68   3rd Qu.: 77.292  
##  Max.   :481.0   Max.   :753.3   Max.   :27.01   Max.   :124.000  
##    Turbidity       Potability    
##  Min.   :1.450   Min.   :0.0000  
##  1st Qu.:3.443   1st Qu.:0.0000  
##  Median :3.968   Median :0.0000  
##  Mean   :3.970   Mean   :0.4033  
##  3rd Qu.:4.514   3rd Qu.:1.0000  
##  Max.   :6.495   Max.   :1.0000</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="day-2.html#cb145-1" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code></pre></div>
<pre><code>## [1] 3276   10</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="day-2.html#cb147-1" tabindex="-1"></a><span class="fu">dim</span>(water_df)</span></code></pre></div>
<pre><code>## [1] 2011   10</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>The Potability column has two possible values: 1 means Potable and 0 means Not potable.</li>
</ol>
<p>It is read in by default as a character vector. Convert this column to a factor.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="day-2.html#cb149-1" tabindex="-1"></a>water_df<span class="sc">$</span>Potability <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(water_df<span class="sc">$</span>Potability)</span>
<span id="cb149-2"><a href="day-2.html#cb149-2" tabindex="-1"></a><span class="fu">head</span>(water_df)</span></code></pre></div>
<pre><code>##           ph Hardness   Solids Chloramines  Sulfate Conductivity Organic_carbon
## 4   8.316766 214.3734 22018.42    8.059332 356.8861     363.2665      18.436524
## 5   9.092223 181.1015 17978.99    6.546600 310.1357     398.4108      11.558279
## 6   5.584087 188.3133 28748.69    7.544869 326.6784     280.4679       8.399735
## 7  10.223862 248.0717 28749.72    7.513408 393.6634     283.6516      13.789695
## 8   8.635849 203.3615 13672.09    4.563009 303.3098     474.6076      12.363817
## 10 11.180284 227.2315 25484.51    9.077200 404.0416     563.8855      17.927806
##    Trihalomethanes Turbidity Potability
## 4        100.34167  4.628771          0
## 5         31.99799  4.075075          0
## 6         54.91786  2.559708          0
## 7         84.60356  2.672989          0
## 8         62.79831  4.401425          0
## 10        71.97660  4.370562          0</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="day-2.html#cb151-1" tabindex="-1"></a><span class="fu">table</span>(water_df<span class="sc">$</span>Potability)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 1200  811</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>WHO has recommended maximum permissible limit of pH in drinking water from 6.5 to 8.5.</li>
</ol>
<p>Create a new column within the <code>water_df</code> object called <code>ph_category</code> in which:</p>
<ul>
<li>Observations with a pH less than 6.5 have a value of <code>acidic</code> in the <code>ph_category</code></li>
<li>Observations with a pH betwee 6.5 - 8.5 have a value of <code>permissible</code> in the <code>ph_category</code></li>
<li>Observations with a pH greater than 8.5 have a value of <code>basic</code> in the <code>ph_category</code></li>
</ul>
<p>There are multiple ways to do this, give it a go! You can’t break the object - if you ever feel like you need a reset, you can always repeat step 1 to read in the object again.</p>
<p>Use <code>table()</code> or <code>summary()</code> to check the values in the <code>ph_category</code> column</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="day-2.html#cb153-1" tabindex="-1"></a>water_df<span class="sc">$</span>ph_category <span class="ot">&lt;-</span> <span class="st">&quot;permissible&quot;</span></span>
<span id="cb153-2"><a href="day-2.html#cb153-2" tabindex="-1"></a></span>
<span id="cb153-3"><a href="day-2.html#cb153-3" tabindex="-1"></a>water_df<span class="sc">$</span>ph_category[water_df<span class="sc">$</span>ph <span class="sc">&lt;</span> <span class="fl">6.5</span>] <span class="ot">&lt;-</span> <span class="st">&quot;acidic&quot;</span> </span>
<span id="cb153-4"><a href="day-2.html#cb153-4" tabindex="-1"></a></span>
<span id="cb153-5"><a href="day-2.html#cb153-5" tabindex="-1"></a>water_df<span class="sc">$</span>ph_category[water_df<span class="sc">$</span>ph <span class="sc">&gt;</span> <span class="fl">8.5</span>] <span class="ot">&lt;-</span> <span class="st">&quot;basic&quot;</span></span>
<span id="cb153-6"><a href="day-2.html#cb153-6" tabindex="-1"></a></span>
<span id="cb153-7"><a href="day-2.html#cb153-7" tabindex="-1"></a><span class="fu">table</span>(water_df<span class="sc">$</span>ph_category)</span></code></pre></div>
<pre><code>## 
##      acidic       basic permissible 
##         692         358         961</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="day-2.html#cb155-1" tabindex="-1"></a><span class="fu">nrow</span>(water_df[water_df<span class="sc">$</span>ph <span class="sc">&lt;</span><span class="fl">6.5</span>, ])</span></code></pre></div>
<pre><code>## [1] 692</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Create a plot to double check if the annotations in the <code>ph_category</code> column were applied correctly. Make sure to represent both the <code>ph</code> and <code>ph_category</code> columns.</li>
</ol>
<p>You’re welcome to use base R or ggplot functions. There are multiple ways of representing these two columns. ggplot is slightly preferred because of its increased customization so it’s good to get some practice with it!</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="day-2.html#cb157-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb157-2"><a href="day-2.html#cb157-2" tabindex="-1"></a><span class="fu">ggplot</span>(water_df, <span class="fu">aes</span>(<span class="at">x=</span>ph_category, <span class="at">y=</span>ph)) <span class="sc">+</span> </span>
<span id="cb157-3"><a href="day-2.html#cb157-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<ol start="6" style="list-style-type: decimal">
<li>The levels of sulfates and water hardness cause by salts should be minimized in order to be safe for consumption.</li>
</ol>
<p>Create a plot with the level of water hardness on the x axis and sulphate on the y axis colored by the Potability column.</p>
<p>Try applying the <code>facet_grid()</code> layer to the plot in order to group the plots by a factor. Make sure to use the <code>~</code> before the column name!</p>
<div class="callout-blue">
<span class="callout-icon"><i class="fas fa-circle-info" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Note</p>
</div>
<p>The data is quite messy so don’t worry if the results do not separate as much as you would like - real data is messy!</p>
</div>
</div>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="day-2.html#cb158-1" tabindex="-1"></a><span class="fu">ggplot</span>(water_df, <span class="fu">aes</span>(<span class="at">x =</span> Hardness, <span class="at">y =</span> Sulfate, <span class="at">col =</span> Potability)) <span class="sc">+</span> </span>
<span id="cb158-2"><a href="day-2.html#cb158-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb158-3"><a href="day-2.html#cb158-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>ph_category) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
</div>
<div id="review-with-datasaurus-dozen" class="section level3 hasAnchor">
<h3>Review with Datasaurus Dozen<a href="day-2.html#review-with-datasaurus-dozen" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Datasaurus Dozen dataset is a handful of data points that complement the <code>dplyr</code> package. Aside from functions, packages can also import objects.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="day-2.html#cb159-1" tabindex="-1"></a><span class="co">#install.packages(&quot;datasauRus&quot;)</span></span>
<span id="cb159-2"><a href="day-2.html#cb159-2" tabindex="-1"></a><span class="fu">library</span>(datasauRus)</span>
<span id="cb159-3"><a href="day-2.html#cb159-3" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="day-2.html#cb160-1" tabindex="-1"></a><span class="fu">summary</span>(datasaurus_dozen)</span></code></pre></div>
<pre><code>##    dataset                x               y           
##  Length:1846        Min.   :15.56   Min.   : 0.01512  
##  Class :character   1st Qu.:41.07   1st Qu.:22.56107  
##  Mode  :character   Median :52.59   Median :47.59445  
##                     Mean   :54.27   Mean   :47.83510  
##                     3rd Qu.:67.28   3rd Qu.:71.81078  
##                     Max.   :98.29   Max.   :99.69468</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="day-2.html#cb162-1" tabindex="-1"></a>datasaurus_dozen<span class="sc">$</span>dataset <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(datasaurus_dozen<span class="sc">$</span>dataset)</span>
<span id="cb162-2"><a href="day-2.html#cb162-2" tabindex="-1"></a></span>
<span id="cb162-3"><a href="day-2.html#cb162-3" tabindex="-1"></a><span class="fu">tail</span>(datasaurus_dozen)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   dataset        x     y
##   &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1 wide_lines  34.7  19.6
## 2 wide_lines  33.7  26.1
## 3 wide_lines  75.6  37.1
## 4 wide_lines  40.6  89.1
## 5 wide_lines  39.1  96.5
## 6 wide_lines  34.6  89.6</code></pre>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="day-2.html#cb164-1" tabindex="-1"></a><span class="fu">table</span>(datasaurus_dozen<span class="sc">$</span>dataset)</span></code></pre></div>
<pre><code>## 
##       away   bullseye     circle       dino       dots    h_lines high_lines 
##        142        142        142        142        142        142        142 
## slant_down   slant_up       star    v_lines wide_lines    x_shape 
##        142        142        142        142        142        142</code></pre>
<p>There are 13 different datasets in this one object. We will use tidyverse functions to take an overview look at the object, grouped by the datasets.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="day-2.html#cb166-1" tabindex="-1"></a>datasaurus_dozen <span class="sc">%&gt;%</span> </span>
<span id="cb166-2"><a href="day-2.html#cb166-2" tabindex="-1"></a>  <span class="fu">group_by</span>(dataset) <span class="sc">%&gt;%</span> </span>
<span id="cb166-3"><a href="day-2.html#cb166-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_x =</span> <span class="fu">mean</span>(x), </span>
<span id="cb166-4"><a href="day-2.html#cb166-4" tabindex="-1"></a>            <span class="at">mean_y =</span> <span class="fu">mean</span>(y), </span>
<span id="cb166-5"><a href="day-2.html#cb166-5" tabindex="-1"></a>            <span class="at">std_dev_x =</span> <span class="fu">sd</span>(x), </span>
<span id="cb166-6"><a href="day-2.html#cb166-6" tabindex="-1"></a>            <span class="at">std_dev_y =</span> <span class="fu">sd</span>(y))</span></code></pre></div>
<pre><code>## # A tibble: 13 × 5
##    dataset    mean_x mean_y std_dev_x std_dev_y
##    &lt;fct&gt;       &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 away         54.3   47.8      16.8      26.9
##  2 bullseye     54.3   47.8      16.8      26.9
##  3 circle       54.3   47.8      16.8      26.9
##  4 dino         54.3   47.8      16.8      26.9
##  5 dots         54.3   47.8      16.8      26.9
##  6 h_lines      54.3   47.8      16.8      26.9
##  7 high_lines   54.3   47.8      16.8      26.9
##  8 slant_down   54.3   47.8      16.8      26.9
##  9 slant_up     54.3   47.8      16.8      26.9
## 10 star         54.3   47.8      16.8      26.9
## 11 v_lines      54.3   47.8      16.8      26.9
## 12 wide_lines   54.3   47.8      16.8      26.9
## 13 x_shape      54.3   47.8      16.8      26.9</code></pre>
<p>All of the datasets have roughly the same mean and standard deviation along both the x and y axis.</p>
<p>Let’s take a look the data graphically. We will use <code>filter</code> to extract the rows belonging to one dataset and then pipe that directly into a ggplot. Both dplyr and ggplot are developed within “the Tidyverse” and can use pipes, but you may not be able to pipe in base R functions or functions from different packages.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="day-2.html#cb168-1" tabindex="-1"></a>datasaurus_dozen <span class="sc">%&gt;%</span> </span>
<span id="cb168-2"><a href="day-2.html#cb168-2" tabindex="-1"></a>  <span class="fu">filter</span>(dataset <span class="sc">==</span> <span class="st">&quot;star&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb168-3"><a href="day-2.html#cb168-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span> <span class="co"># PLUS SIGN, NOT PIPE FOR THIS ONE</span></span>
<span id="cb168-4"><a href="day-2.html#cb168-4" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>Tidyverse’s data wranging packages use the pipe <code>%&gt;%</code> to move the previous output to the next line, where as ggplot uses the plus sign <code>+</code></p>
<p>Try editing the code above to display different datasets. Notice how different groups of data points can all give similar statistical summaries - so it’s always a good choice to visualize your data rather than relying on just numbers.</p>
<p>If we wanted to take a look at all of the datasets at once, we can also use the <code>facet_wrap()</code> function.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="day-2.html#cb169-1" tabindex="-1"></a>datasaurus_dozen <span class="sc">%&gt;%</span> </span>
<span id="cb169-2"><a href="day-2.html#cb169-2" tabindex="-1"></a>  <span class="co">#filter(dataset == &quot;star&quot;) %&gt;%  REMOVE THIS ROW</span></span>
<span id="cb169-3"><a href="day-2.html#cb169-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span> </span>
<span id="cb169-4"><a href="day-2.html#cb169-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb169-5"><a href="day-2.html#cb169-5" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>dataset)<span class="sc">+</span> <span class="fu">theme_void</span>() <span class="co"># ADD THIS LINE</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="day-2.html#cb170-1" tabindex="-1"></a><span class="fu">head</span>(datasaurus_dozen)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   dataset     x     y
##   &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 dino     55.4  97.2
## 2 dino     51.5  96.0
## 3 dino     46.2  94.5
## 4 dino     42.8  91.4
## 5 dino     40.8  88.3
## 6 dino     38.7  84.9</code></pre>
</div>
<div id="generalizable-code" class="section level3 hasAnchor">
<h3>Generalizable Code<a href="day-2.html#generalizable-code" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A major strength of programming is the ability to automate repetitive tasks. As a general rule of thumb, if you need to do a task more than three times (ex. analyzing multiple PCR plates or integrating clinical data from multiple days), it is worth it to invest time to write generalizable code or a custom function.</p>
<p>Now that we’re getting comfortable writing code, we will spend some time revisiting code that we wrote to make them generalizable and even better! Generalizable means that the code is flexible and can be applied to multiple similar objects. For example, if we’re running a clinical study and we have patient demographic data from multiple sites, we want to check that the mean patient demographic is comparable between sites by creating similar plots of each hospital site to compare. If we write code for one location and then copy and paste it into another code chunk to apply to the next location, the code may require some modification before it works.</p>
<p>Generalizable code begins at data collection. Depending on your workflow, you may or may not be able to influence this stage of the analysis. If possible, it is best practice to keep the column names and entries for categorical variables consistent. For example, when recording the age of patients, “6”, “6”, “six”, and “Six” are all considered different levels of the factor so you will need to either make sure data collection is consistent or check and correct these inconsistencies in your code. Get into a habit of checking your work. Whether it is code you’ve written yourself, code you you’ve been sent by a collaborator, or published data from a biobank - never assume the data is as you predicted.</p>
</div>
<div id="generalizable-plots" class="section level3 hasAnchor">
<h3>Generalizable Plots<a href="day-2.html#generalizable-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Remember when we edited our code to test out multiple datasets in the datasaurus dozen object? Perhaps you copy and pasted the code several time and changed the column name? This is not optimal because if you need to change the code in one instance (for example changing the x-axis label), you’ll need to revisit ever instance that you copy and pasted to code to. This approach leads you vulnerable to errors when copy and pasting.</p>
<p>One way to make your code robust is to bring all the factors that need editing to the start of the data. This may seem cumbersome for such a simple example where we are only changing the dataset name, but we’ll return to this concept later with more complicated examples.</p>
<p>Let’s grab the code we used to make one plot earlier and modify it to be more generalizable</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="day-2.html#cb172-1" tabindex="-1"></a><span class="fu">levels</span>(datasaurus_dozen<span class="sc">$</span>dataset)</span></code></pre></div>
<pre><code>##  [1] &quot;away&quot;       &quot;bullseye&quot;   &quot;circle&quot;     &quot;dino&quot;       &quot;dots&quot;      
##  [6] &quot;h_lines&quot;    &quot;high_lines&quot; &quot;slant_down&quot; &quot;slant_up&quot;   &quot;star&quot;      
## [11] &quot;v_lines&quot;    &quot;wide_lines&quot; &quot;x_shape&quot;</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="day-2.html#cb174-1" tabindex="-1"></a>dataset_name <span class="ot">&lt;-</span> <span class="st">&quot;dino&quot;</span> <span class="co"># ADD THIS LINE</span></span>
<span id="cb174-2"><a href="day-2.html#cb174-2" tabindex="-1"></a></span>
<span id="cb174-3"><a href="day-2.html#cb174-3" tabindex="-1"></a>datasaurus_dozen <span class="sc">%&gt;%</span> </span>
<span id="cb174-4"><a href="day-2.html#cb174-4" tabindex="-1"></a>  <span class="fu">filter</span>(dataset <span class="sc">==</span> dataset_name) <span class="sc">%&gt;%</span> <span class="co"># Remove comment # CHANGE VARIABLE NAME</span></span>
<span id="cb174-5"><a href="day-2.html#cb174-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span> </span>
<span id="cb174-6"><a href="day-2.html#cb174-6" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="co"># REMOVE THE + at the end of the line</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<p>Once we have converted our code to a generalized format, we can convert it into a more versatile custom function!</p>
<p>Curly brackets are used for inputting multiple lines of code. It is generally attached to the function that proceeds it.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="day-2.html#cb175-1" tabindex="-1"></a><span class="co"># dataset_name &lt;- &quot;dino&quot; # ADD THIS LINE</span></span>
<span id="cb175-2"><a href="day-2.html#cb175-2" tabindex="-1"></a></span>
<span id="cb175-3"><a href="day-2.html#cb175-3" tabindex="-1"></a>dino_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(data_name) {</span>
<span id="cb175-4"><a href="day-2.html#cb175-4" tabindex="-1"></a>  datasaurus_dozen <span class="sc">%&gt;%</span> </span>
<span id="cb175-5"><a href="day-2.html#cb175-5" tabindex="-1"></a>    <span class="fu">filter</span>(dataset <span class="sc">==</span> data_name) <span class="sc">%&gt;%</span> <span class="co"># CHANGE ARGUMENT NAME</span></span>
<span id="cb175-6"><a href="day-2.html#cb175-6" tabindex="-1"></a>    </span>
<span id="cb175-7"><a href="day-2.html#cb175-7" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span> </span>
<span id="cb175-8"><a href="day-2.html#cb175-8" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb175-9"><a href="day-2.html#cb175-9" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb175-10"><a href="day-2.html#cb175-10" tabindex="-1"></a>}</span>
<span id="cb175-11"><a href="day-2.html#cb175-11" tabindex="-1"></a></span>
<span id="cb175-12"><a href="day-2.html#cb175-12" tabindex="-1"></a><span class="fu">dino_plot</span>(<span class="st">&quot;dino&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="day-2.html#cb176-1" tabindex="-1"></a><span class="fu">dino_plot</span>(<span class="st">&quot;circle&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-72-2.png" width="672" /></p>
</div>
<div id="exercise-3" class="section level3 hasAnchor">
<h3>Exercise<a href="day-2.html#exercise-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ve now encountered round brackets <code>()</code>, square brackets <code>[]</code>, and curly brackets<code>{}</code> - each have their own distinct functions! Take a few moments to chat with your neighbors and outline cases in which we’ve used each bracket and what is their role in R syntax.</p>
<p>round brackets ()
come after a function, function will apply to whatever is in the brackets
functionName(what is being acted on)</p>
<p>square brackets []
Indexing, locations
object[position]
dataframe[rows, cols]</p>
<p>curly brackets {}
Used in function, indicate multiple lines of related code
Rmd – indicates language in code chunk</p>
</div>
<div id="dataset---heart-stroke-prediction" class="section level3 hasAnchor">
<h3>Dataset - Heart Stroke Prediction<a href="day-2.html#dataset---heart-stroke-prediction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The dataset we will be working with for today’s workshop contains clinical data collected with the aim of predicting whether a patient is likely to suffer a stroke.</p>
<p>The dataset can be found: <a href="https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset" class="uri">https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset</a></p>
<p>Here is some more information about the columns in this dataset:</p>
<ol style="list-style-type: decimal">
<li>id: unique identifier</li>
<li>gender: “Male”, “Female” or “Other”</li>
<li>age: age of the patient</li>
<li>hypertension: 0 if the patient doesn’t have hypertension, 1 if the patient has hypertension</li>
<li>heart_disease: 0 if the patient doesn’t have any heart diseases, 1 if the patient has a heart disease</li>
<li>ever_married: “No” or “Yes”</li>
<li>work_type: “children”, “Govt_jov”, “Never_worked”, “Private” or “Self-employed”</li>
<li>Residence_type: “Rural” or “Urban”</li>
<li>avg_glucose_level: average glucose level in blood</li>
<li>bmi: body mass index</li>
<li>smoking_status: “formerly smoked”, “never smoked”, “smokes” or “Unknown”*</li>
<li>stroke: 1 if the patient had a stroke or 0 if not</li>
</ol>
<div class="callout-blue">
<span class="callout-icon"><i class="fas fa-circle-info" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Note</p>
</div>
<p>“Unknown” in smoking_status means that the information is unavailable for this patient</p>
</div>
</div>
<p>Let’s get started!</p>
</div>
<div id="exercise-4" class="section level3 hasAnchor">
<h3>Exercise<a href="day-2.html#exercise-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Reading in the dataset can be an intimidating step when you’re just starting out with programming. Since this is a csv file, we can use the appropriately named <code>read.csv()</code> function. In cases when you have other file types such as .txt or .tab files that are tab deliminated, there is also a <code>read.table()</code> function that is more universal (but requires more parameters to let R know how your data is stored).</p>
<p>Read in the <code>healthcare-dataset-stroke-data.csv</code> into an object called <code>heart</code>. Check your object using head and/or summary functions. Toggle a parameter called <code>stringsAsFactors</code> to <code>TRUE</code> in order to automatically import character values as factors rather than characters</p>
<div class="callout-orange">
<span class="callout-icon"><i class="fas fa-fire" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Tip</p>
</div>
<p>Make sure the dataset is in the same directory or folder as this .Rmd file for ease of import</p>
</div>
</div>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="day-2.html#cb177-1" tabindex="-1"></a>heart <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;../INR-2024/datasets/healthcare-dataset-stroke-data.csv&quot;</span>, <span class="at">stringsAsFactors=</span><span class="cn">TRUE</span>)</span>
<span id="cb177-2"><a href="day-2.html#cb177-2" tabindex="-1"></a></span>
<span id="cb177-3"><a href="day-2.html#cb177-3" tabindex="-1"></a><span class="fu">head</span>(heart)</span></code></pre></div>
<pre><code>##      id gender age hypertension heart_disease ever_married     work_type
## 1  9046   Male  67            0             1          Yes       Private
## 2 51676 Female  61            0             0          Yes Self-employed
## 3 31112   Male  80            0             1          Yes       Private
## 4 60182 Female  49            0             0          Yes       Private
## 5  1665 Female  79            1             0          Yes Self-employed
## 6 56669   Male  81            0             0          Yes       Private
##   Residence_type avg_glucose_level  bmi  smoking_status stroke
## 1          Urban            228.69 36.6 formerly smoked      1
## 2          Rural            202.21  N/A    never smoked      1
## 3          Rural            105.92 32.5    never smoked      1
## 4          Urban            171.23 34.4          smokes      1
## 5          Rural            174.12   24    never smoked      1
## 6          Urban            186.21   29 formerly smoked      1</code></pre>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="day-2.html#cb179-1" tabindex="-1"></a><span class="fu">str</span>(heart)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    5110 obs. of  12 variables:
##  $ id               : int  9046 51676 31112 60182 1665 56669 53882 10434 27419 60491 ...
##  $ gender           : Factor w/ 6 levels &quot;female&quot;,&quot;Female&quot;,..: 4 2 4 2 2 4 4 2 2 2 ...
##  $ age              : num  67 61 80 49 79 81 74 69 59 78 ...
##  $ hypertension     : Factor w/ 4 levels &quot;0&quot;,&quot;1&quot;,&quot;10&quot;,&quot;10+D4972&quot;: 1 1 1 1 2 1 2 1 1 1 ...
##  $ heart_disease    : int  1 0 1 0 0 0 1 0 0 0 ...
##  $ ever_married     : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 2 2 2 2 2 2 2 1 2 2 ...
##  $ work_type        : Factor w/ 8 levels &quot;children&quot;,&quot;Govt_job&quot;,..: 5 7 5 5 7 5 5 5 5 5 ...
##  $ Residence_type   : Factor w/ 2 levels &quot;Rural&quot;,&quot;Urban&quot;: 2 1 1 2 1 2 1 2 1 2 ...
##  $ avg_glucose_level: num  229 202 106 171 174 ...
##  $ bmi              : Factor w/ 419 levels &quot;10.3&quot;,&quot;11.3&quot;,..: 240 419 199 218 114 164 148 102 419 116 ...
##  $ smoking_status   : Factor w/ 4 levels &quot;formerly smoked&quot;,..: 1 2 2 3 2 1 2 2 4 4 ...
##  $ stroke           : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="day-2.html#cb181-1" tabindex="-1"></a><span class="co"># Hypertension has values that are typos, need to be removed </span></span>
<span id="cb181-2"><a href="day-2.html#cb181-2" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>hypertension)</span></code></pre></div>
<pre><code>## 
##        0        1       10 10+D4972 
##     4612      493        4        1</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="day-2.html#cb183-1" tabindex="-1"></a><span class="co"># Stroke and heart.disease need to be categorical </span></span>
<span id="cb183-2"><a href="day-2.html#cb183-2" tabindex="-1"></a><span class="fu">summary</span>(heart<span class="sc">$</span>stroke)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00000 0.00000 0.00000 0.04873 0.00000 1.00000</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="day-2.html#cb185-1" tabindex="-1"></a><span class="co"># Gender has some variability </span></span>
<span id="cb185-2"><a href="day-2.html#cb185-2" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## female Female   male   Male   meal  Other 
##      7   2987      6   2108      1      1</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="day-2.html#cb187-1" tabindex="-1"></a><span class="co"># Abnormal BMI value AND convert from factor to numeric </span></span>
<span id="cb187-2"><a href="day-2.html#cb187-2" tabindex="-1"></a><span class="fu">summary</span>(heart<span class="sc">$</span>bmi)</span></code></pre></div>
<pre><code>##     N/A    28.7    28.4    26.1    26.7    27.6    27.7    23.4    27.3      27 
##     201      41      38      37      37      37      37      36      36      35 
##    25.1    26.4    26.9    25.5    23.5    24.8    28.9    22.2    26.5    28.3 
##      34      34      34      33      31      31      31      30      30      30 
##    29.4    30.3    31.4    24.2    26.6    27.5    28.1    29.1      24    24.1 
##      30      30      30      29      29      29      29      29      28      28 
##    25.3    27.1    27.9      28    32.3    21.5      23    24.9      25    26.2 
##      28      28      28      28      28      27      27      27      27      27 
##    28.5    28.6    29.7      30    30.9    31.5    24.3    24.5    25.4    28.8 
##      27      27      27      27      27      27      26      26      26      26 
##      29    29.2    29.5    29.6    29.9    30.1    31.1    20.1    22.7    22.8 
##      26      26      26      26      26      26      26      25      25      25 
##      26    28.2    32.8    33.1    23.6    23.9    25.8    25.9    27.2    30.5 
##      25      25      25      25      24      24      24      24      24      24 
##    31.8    32.1    35.8    20.4    24.4    26.3    27.8    29.8    30.7    33.5 
##      24      24      24      23      23      23      23      23      23      23 
##    21.4    22.1    22.4    23.8    24.6    24.7    27.4    29.3      31    31.9 
##      22      22      22      22      22      22      22      22      22      22 
##    19.5    21.3    23.1    25.6    26.8    30.8    31.3    31.6      32 (Other) 
##      21      21      21      21      21      21      21      21      21    2282</code></pre>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="day-2.html#cb189-1" tabindex="-1"></a><span class="co"># Age, very low value of 0.08</span></span>
<span id="cb189-2"><a href="day-2.html#cb189-2" tabindex="-1"></a><span class="fu">str</span>(heart) </span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    5110 obs. of  12 variables:
##  $ id               : int  9046 51676 31112 60182 1665 56669 53882 10434 27419 60491 ...
##  $ gender           : Factor w/ 6 levels &quot;female&quot;,&quot;Female&quot;,..: 4 2 4 2 2 4 4 2 2 2 ...
##  $ age              : num  67 61 80 49 79 81 74 69 59 78 ...
##  $ hypertension     : Factor w/ 4 levels &quot;0&quot;,&quot;1&quot;,&quot;10&quot;,&quot;10+D4972&quot;: 1 1 1 1 2 1 2 1 1 1 ...
##  $ heart_disease    : int  1 0 1 0 0 0 1 0 0 0 ...
##  $ ever_married     : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 2 2 2 2 2 2 2 1 2 2 ...
##  $ work_type        : Factor w/ 8 levels &quot;children&quot;,&quot;Govt_job&quot;,..: 5 7 5 5 7 5 5 5 5 5 ...
##  $ Residence_type   : Factor w/ 2 levels &quot;Rural&quot;,&quot;Urban&quot;: 2 1 1 2 1 2 1 2 1 2 ...
##  $ avg_glucose_level: num  229 202 106 171 174 ...
##  $ bmi              : Factor w/ 419 levels &quot;10.3&quot;,&quot;11.3&quot;,..: 240 419 199 218 114 164 148 102 419 116 ...
##  $ smoking_status   : Factor w/ 4 levels &quot;formerly smoked&quot;,..: 1 2 2 3 2 1 2 2 4 4 ...
##  $ stroke           : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>Before we dive into this dataset, we get a very limited indication that the object is read in correctly by checking the Environment panel - you’ll notice the new <code>heart</code> appears under Data and it lets us know that there are 5110 observations (number of patients) and 12 variables (number of clinical features with entries). You can also double click the name of the object here to open up a view of the whole dataset - caution that this can cause your machine to stall if the dataset is exceptionally large and/or your machine is running on minimal memory.</p>
</div>
<div id="exercise-5" class="section level3 hasAnchor">
<h3>Exercise<a href="day-2.html#exercise-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Explore the dataset! Take a look at the columns and identify some potential issues with this dataset that either warrant further investigation or correction.</p>
<p>There is no universally right or wrong way to do this. Perhaps the only truly incorrect way of doing this is going through the dataset which is thousands of observations line by line.</p>
</div>
<div id="factors" class="section level3 hasAnchor">
<h3>Factors<a href="day-2.html#factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>stringsAsFactors</code> parameter takes care of the character values but we still have some integer values that should be interpreted as factors.</p>
<p>When deciding on whether a number is a factor or should be kept numeric, consider if decimals/numbers-in-between make sense. The first two entries for <code>avg_glucose_level</code> are 229 and 202 - a glucose level in between would be reasonable. In contrast, the first to entries for <code>heart_disease</code> are 1 and 0 - as these are coding for having or not having the disorder, an entry of 1.2 does not make sense.</p>
<p>Recall from the introduction to the dataset from above:
4) hypertension: 0 if the patient doesn’t have hypertension, 1 if the patient has hypertension
5) heart_disease: 0 if the patient doesn’t have any heart diseases, 1 if the patient has a heart disease
12) stroke: 1 if the patient had a stroke or 0 if not</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="day-2.html#cb191-1" tabindex="-1"></a>heart<span class="sc">$</span>hypertension <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(heart<span class="sc">$</span>hypertension)</span>
<span id="cb191-2"><a href="day-2.html#cb191-2" tabindex="-1"></a>heart<span class="sc">$</span>heart_disease <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(heart<span class="sc">$</span>heart_disease)</span>
<span id="cb191-3"><a href="day-2.html#cb191-3" tabindex="-1"></a>heart<span class="sc">$</span>stroke <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(heart<span class="sc">$</span>stroke)</span>
<span id="cb191-4"><a href="day-2.html#cb191-4" tabindex="-1"></a></span>
<span id="cb191-5"><a href="day-2.html#cb191-5" tabindex="-1"></a><span class="fu">summary</span>(heart)</span></code></pre></div>
<pre><code>##        id           gender          age          hypertension  heart_disease
##  Min.   :   67   female:   7   Min.   : 0.08   0       :4612   0:4834       
##  1st Qu.:17741   Female:2987   1st Qu.:25.00   1       : 493   1: 276       
##  Median :36932   male  :   6   Median :45.00   10      :   4                
##  Mean   :36518   Male  :2108   Mean   :43.23   10+D4972:   1                
##  3rd Qu.:54682   meal  :   1   3rd Qu.:61.00                                
##  Max.   :72940   Other :   1   Max.   :82.00                                
##                                                                             
##  ever_married         work_type    Residence_type avg_glucose_level
##  No :1757     Private      :2921   Rural:2514     Min.   : 55.12   
##  Yes:3353     Self-employed: 818   Urban:2596     1st Qu.: 77.25   
##               children     : 687                  Median : 91.89   
##               Govt_job     : 656                  Mean   :106.15   
##               Never_worked :  22                  3rd Qu.:114.09   
##               Private      :   4                  Max.   :271.74   
##               (Other)      :   2                                   
##       bmi               smoking_status stroke  
##  N/A    : 201   formerly smoked: 885   0:4861  
##  28.7   :  41   never smoked   :1892   1: 249  
##  28.4   :  38   smokes         : 789           
##  26.1   :  37   Unknown        :1544           
##  26.7   :  37                                  
##  27.6   :  37                                  
##  (Other):4719</code></pre>
</div>
<div id="incomplete-data" class="section level3 hasAnchor">
<h3>Incomplete Data<a href="day-2.html#incomplete-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Firstly, we have to make a decision on how to handle missing values. We can either accept that some of the columns are incomplete or eliminate rows that do not have full data. Let’s evaluate which columns this affects</p>
<p>If you ever encounter missing data when you are entering data, use <code>NA</code>.</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="day-2.html#cb193-1" tabindex="-1"></a><span class="fu">ggplot</span>(heart, <span class="fu">aes</span>(<span class="at">x =</span> smoking_status, <span class="at">fill =</span> hypertension)) <span class="sc">+</span> </span>
<span id="cb193-2"><a href="day-2.html#cb193-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-76-1.png" width="672" /></p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="day-2.html#cb194-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(heart<span class="sc">$</span>smoking_status, heart<span class="sc">$</span>hypertension))</span></code></pre></div>
<pre><code>##                  
##                              0            1           10     10+D4972
##   formerly smoked 0.1497064579 0.0232876712 0.0001956947 0.0000000000
##   never smoked    0.3248532290 0.0448140900 0.0003913894 0.0001956947
##   smokes          0.1360078278 0.0183953033 0.0000000000 0.0000000000
##   Unknown         0.2919765166 0.0099804305 0.0001956947 0.0000000000</code></pre>
<p>Let’s use tidyverse to remove the rows in the <code>smoking_status</code> column with a value of <code>Unknown</code>.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="day-2.html#cb196-1" tabindex="-1"></a><span class="fu">dim</span>(heart) <span class="co"># original 5110 rows </span></span></code></pre></div>
<pre><code>## [1] 5110   12</code></pre>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="day-2.html#cb198-1" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>smoking_status) <span class="co">#1544 unknowns</span></span></code></pre></div>
<pre><code>## 
## formerly smoked    never smoked          smokes         Unknown 
##             885            1892             789            1544</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="day-2.html#cb200-1" tabindex="-1"></a><span class="fu">dim</span>(<span class="fu">filter</span>(heart, <span class="sc">!</span>(smoking_status <span class="sc">==</span> <span class="st">&quot;Unknown&quot;</span>)))</span></code></pre></div>
<pre><code>## [1] 3566   12</code></pre>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="day-2.html#cb202-1" tabindex="-1"></a>heart <span class="ot">&lt;-</span> <span class="fu">filter</span>(heart, <span class="sc">!</span>(smoking_status <span class="sc">==</span> <span class="st">&quot;Unknown&quot;</span>))</span>
<span id="cb202-2"><a href="day-2.html#cb202-2" tabindex="-1"></a><span class="fu">summary</span>(heart<span class="sc">$</span>smoking_status)</span></code></pre></div>
<pre><code>## formerly smoked    never smoked          smokes         Unknown 
##             885            1892             789               0</code></pre>
<p>After double checking, we can see that the smoking status has an empty level, we’ll clean this up before moving on</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="day-2.html#cb204-1" tabindex="-1"></a>heart<span class="sc">$</span>smoking_status <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(heart<span class="sc">$</span>smoking_status)</span>
<span id="cb204-2"><a href="day-2.html#cb204-2" tabindex="-1"></a></span>
<span id="cb204-3"><a href="day-2.html#cb204-3" tabindex="-1"></a><span class="fu">summary</span>(heart<span class="sc">$</span>smoking_status)</span></code></pre></div>
<pre><code>## formerly smoked    never smoked          smokes 
##             885            1892             789</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="day-2.html#cb206-1" tabindex="-1"></a>heart_checkpoint <span class="ot">&lt;-</span> heart</span></code></pre></div>
<p>Great! Now let’s tackle the typos in the gender column.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="day-2.html#cb207-1" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## female Female   male   Male   meal  Other 
##      5   2153      5   1402      0      1</code></pre>
<p>We need to fix the typos that happened during data entry and the single observation of <code>Other</code> will not be enough data for us to draw any statistical conclusion so we’ll remove this row while we’re at it.</p>
<p>We can use <code>str_replace_all()</code> as a search and replace tool</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="day-2.html#cb209-1" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">str_replace_all</span>(heart<span class="sc">$</span>gender, <span class="st">&quot;female&quot;</span>, <span class="st">&quot;Female&quot;</span>))</span></code></pre></div>
<pre><code>## 
## Female   male   Male  Other 
##   2158      5   1402      1</code></pre>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="day-2.html#cb211-1" tabindex="-1"></a><span class="co"># str_replace_all(data, what we&#39;re search, what to replace with)</span></span></code></pre></div>
<p>Remember that this only displays the output, it does not replace the columns in the dataset.</p>
<p>Before we apply it globally, we can set up a quick double check to make sure that the right values are changed.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="day-2.html#cb212-1" tabindex="-1"></a><span class="co"># document which rows have the error &quot;female&quot; </span></span>
<span id="cb212-2"><a href="day-2.html#cb212-2" tabindex="-1"></a>wrong_entry <span class="ot">&lt;-</span> <span class="fu">which</span>(heart<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">&quot;female&quot;</span>)</span>
<span id="cb212-3"><a href="day-2.html#cb212-3" tabindex="-1"></a>wrong_entry</span></code></pre></div>
<pre><code>## [1]  127  271  941 1930 3021</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="day-2.html#cb214-1" tabindex="-1"></a>heart<span class="sc">$</span>gender[wrong_entry]</span></code></pre></div>
<pre><code>## [1] female female female female female
## Levels: female Female male Male meal Other</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="day-2.html#cb216-1" tabindex="-1"></a><span class="co"># apply the search and replace</span></span>
<span id="cb216-2"><a href="day-2.html#cb216-2" tabindex="-1"></a>heart<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(heart<span class="sc">$</span>gender, <span class="fu">c</span>(<span class="st">&quot;female&quot;</span> <span class="ot">=</span> <span class="st">&quot;Female&quot;</span>, </span>
<span id="cb216-3"><a href="day-2.html#cb216-3" tabindex="-1"></a>                                                <span class="st">&quot;male&quot;</span> <span class="ot">=</span> <span class="st">&quot;Male&quot;</span>, </span>
<span id="cb216-4"><a href="day-2.html#cb216-4" tabindex="-1"></a>                                                <span class="st">&quot;meal&quot;</span> <span class="ot">=</span> <span class="st">&quot;Male&quot;</span>))</span>
<span id="cb216-5"><a href="day-2.html#cb216-5" tabindex="-1"></a></span>
<span id="cb216-6"><a href="day-2.html#cb216-6" tabindex="-1"></a>heart<span class="sc">$</span>gender[wrong_entry]</span></code></pre></div>
<pre><code>## [1] &quot;FeMale&quot; &quot;FeMale&quot; &quot;FeMale&quot; &quot;FeMale&quot; &quot;FeMale&quot;</code></pre>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="day-2.html#cb218-1" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## FeMale   Male  Other 
##   2158   1407      1</code></pre>
<p>There’s an issue with the “male” search grabbing from the “female” word!! Good thing we made a checkpoint earlier. Let’s bring this back to our main heart object - it’s a good habit to make some objects to checkpoint your work. In case you have not had this set up, you can always back track in your code and re-read in the object and re-run some earlier code to catch up.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="day-2.html#cb220-1" tabindex="-1"></a>heart <span class="ot">&lt;-</span> heart_checkpoint </span>
<span id="cb220-2"><a href="day-2.html#cb220-2" tabindex="-1"></a></span>
<span id="cb220-3"><a href="day-2.html#cb220-3" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## female Female   male   Male   meal  Other 
##      5   2153      5   1402      0      1</code></pre>
<p>Let’s try this again:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="day-2.html#cb222-1" tabindex="-1"></a><span class="co"># From previous code </span></span>
<span id="cb222-2"><a href="day-2.html#cb222-2" tabindex="-1"></a></span>
<span id="cb222-3"><a href="day-2.html#cb222-3" tabindex="-1"></a><span class="co"># add ^ (carrot) to the start of the search term to make sure it&#39;s only found at the start of the word</span></span>
<span id="cb222-4"><a href="day-2.html#cb222-4" tabindex="-1"></a>heart<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(heart<span class="sc">$</span>gender, <span class="fu">c</span>(<span class="st">&quot;^female&quot;</span> <span class="ot">=</span> <span class="st">&quot;Female&quot;</span>, </span>
<span id="cb222-5"><a href="day-2.html#cb222-5" tabindex="-1"></a>                                                <span class="st">&quot;^male&quot;</span> <span class="ot">=</span> <span class="st">&quot;Male&quot;</span>, </span>
<span id="cb222-6"><a href="day-2.html#cb222-6" tabindex="-1"></a>                                                <span class="st">&quot;^meal&quot;</span> <span class="ot">=</span> <span class="st">&quot;Male&quot;</span>))</span>
<span id="cb222-7"><a href="day-2.html#cb222-7" tabindex="-1"></a></span>
<span id="cb222-8"><a href="day-2.html#cb222-8" tabindex="-1"></a>heart<span class="sc">$</span>gender[wrong_entry]</span></code></pre></div>
<pre><code>## [1] &quot;Female&quot; &quot;Female&quot; &quot;Female&quot; &quot;Female&quot; &quot;Female&quot;</code></pre>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="day-2.html#cb224-1" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## Female   Male  Other 
##   2158   1407      1</code></pre>
<p>The <code>^</code> is a special character that indicates the start of a word.</p>
<p>Lastly, we’ll the one <code>Other</code> entry</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="day-2.html#cb226-1" tabindex="-1"></a>heart <span class="ot">&lt;-</span> heart[<span class="sc">!</span>heart<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">&quot;Other&quot;</span>, ] <span class="co"># object[rows, col]</span></span>
<span id="cb226-2"><a href="day-2.html#cb226-2" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## Female   Male 
##   2158   1407</code></pre>
<p>Overall, the data is looking much cleaner than when we started!</p>
</div>
<div id="exercise-6" class="section level3 hasAnchor">
<h3>Exercise<a href="day-2.html#exercise-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Investigate the <code>work_type</code> column and correct the data entry problems! Also, remove any “N/A” entries under <code>bmi</code></p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="day-2.html#cb228-1" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>work_type)</span></code></pre></div>
<pre><code>## 
##       children       Govt_job      Govt_job    Never_worked        Private 
##             69            534              1             14           2281 
##       Private   Self-employed Self-employed  
##              3            662              1</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="day-2.html#cb230-1" tabindex="-1"></a><span class="fu">levels</span>(heart<span class="sc">$</span>work_type)</span></code></pre></div>
<pre><code>## [1] &quot;children&quot;       &quot;Govt_job&quot;       &quot;Govt_job &quot;      &quot;Never_worked&quot;  
## [5] &quot;Private&quot;        &quot;Private &quot;       &quot;Self-employed&quot;  &quot;Self-employed &quot;</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="day-2.html#cb232-1" tabindex="-1"></a>heart<span class="sc">$</span>work_type <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(heart<span class="sc">$</span>work_type, <span class="fu">c</span>(<span class="st">&quot;Govt_job &quot;</span> <span class="ot">=</span> <span class="st">&quot;Govt_job&quot;</span>, </span>
<span id="cb232-2"><a href="day-2.html#cb232-2" tabindex="-1"></a>                                                      <span class="st">&quot;Private &quot;</span> <span class="ot">=</span> <span class="st">&quot;Private&quot;</span>, </span>
<span id="cb232-3"><a href="day-2.html#cb232-3" tabindex="-1"></a>                                                      <span class="st">&quot;Self-employed &quot;</span> <span class="ot">=</span> <span class="st">&quot;Self-employed&quot;</span>))</span>
<span id="cb232-4"><a href="day-2.html#cb232-4" tabindex="-1"></a></span>
<span id="cb232-5"><a href="day-2.html#cb232-5" tabindex="-1"></a><span class="fu">class</span>(heart<span class="sc">$</span>work_type)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="day-2.html#cb234-1" tabindex="-1"></a>heart<span class="sc">$</span>work_type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(heart<span class="sc">$</span>work_type)</span></code></pre></div>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="day-2.html#cb235-1" tabindex="-1"></a><span class="fu">summary</span>(heart<span class="sc">$</span>bmi)</span></code></pre></div>
<pre><code>##     N/A    28.4    28.7      27    27.6    25.5    27.3    26.1    26.7    26.9 
##     140      32      32      30      30      28      28      26      26      26 
##    32.3    25.1    25.3    26.4    26.5    27.7    28.3    28.9      29    29.6 
##      26      25      25      25      25      25      25      24      24      24 
##    30.3    30.9    31.4    23.4      28    28.1    28.6    29.4    23.5    26.6 
##      24      24      24      23      23      23      23      23      22      22 
##    27.1    27.5    28.2    28.5    29.5    31.1    22.2    24.5      25    26.2 
##      22      22      22      22      22      22      21      21      21      21 
##    27.9    29.2    29.9      30    30.5    30.7    31.5    32.1      24    24.1 
##      21      21      21      21      21      21      21      21      20      20 
##    24.2    24.3    24.8      26    27.2    30.1    33.1    35.8    24.9    25.4 
##      20      20      20      20      20      20      20      20      19      19 
##    28.8    29.7    31.3    32.8    24.4    26.3    27.8    33.7    21.5    22.8 
##      19      19      19      19      18      18      18      18      17      17 
##    23.1    23.8    27.4    29.3      31    31.6    31.8    34.7    21.3    22.1 
##      17      17      17      17      17      17      17      17      16      16 
##    22.7      23    23.9    24.6    24.7    25.8    25.9    26.8    29.1    29.8 
##      16      16      16      16      16      16      16      16      16      16 
##    30.2    30.8    31.2    31.9    32.4    33.5    34.5    23.6    32.2 (Other) 
##      16      16      16      16      16      16      16      15      15    1414</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="day-2.html#cb237-1" tabindex="-1"></a>heart<span class="sc">$</span>bmi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(heart<span class="sc">$</span>bmi)</span>
<span id="cb237-2"><a href="day-2.html#cb237-2" tabindex="-1"></a><span class="fu">summary</span>(heart<span class="sc">$</span>bmi)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     3.0   128.0   168.0   185.6   223.0   419.0</code></pre>
</div>
<div id="loops" class="section level3 hasAnchor">
<h3>Loops<a href="day-2.html#loops" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>“For loops” allow R to apply highly automated tasks. It will cycle through a range of inputs and “for” each of them, it will carry out your custom task.</p>
<p>Here’s a very simple example to show you the structure of for loops</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="day-2.html#cb239-1" tabindex="-1"></a>fruits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;strawberry&quot;</span>, <span class="st">&quot;banana&quot;</span>, <span class="st">&quot;orange&quot;</span>)</span>
<span id="cb239-2"><a href="day-2.html#cb239-2" tabindex="-1"></a></span>
<span id="cb239-3"><a href="day-2.html#cb239-3" tabindex="-1"></a><span class="cf">for</span>(x <span class="cf">in</span> fruits) {</span>
<span id="cb239-4"><a href="day-2.html#cb239-4" tabindex="-1"></a>  <span class="fu">print</span>(x)</span>
<span id="cb239-5"><a href="day-2.html#cb239-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;strawberry&quot;
## [1] &quot;banana&quot;
## [1] &quot;orange&quot;</code></pre>
<p>The <code>for()</code> function accepts firstly the name of a temporary object that exists only within the curly brackets of the for loop, the <code>in</code> is a special R syntax specification, and <code>fruit</code> is the object that we are applying the for loop on.</p>
<p>The for loop will take each entry of the fruits object, store it in the temporary object <code>x</code>, and apply the code written written within the curly bracket before repeating with the next entry.</p>
<p>I recommend testing your code outside the <code>for()</code> loop before moving it into the loop to make sure it is robust and if you are applying the loop to a long vector or large dataset, consider trying it on a truncated version first as a proof of principle.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="day-2.html#cb241-1" tabindex="-1"></a><span class="fu">levels</span>(heart<span class="sc">$</span>smoking_status)</span></code></pre></div>
<pre><code>## [1] &quot;formerly smoked&quot; &quot;never smoked&quot;    &quot;smokes&quot;</code></pre>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="day-2.html#cb243-1" tabindex="-1"></a>heart <span class="sc">%&gt;%</span> </span>
<span id="cb243-2"><a href="day-2.html#cb243-2" tabindex="-1"></a>  <span class="fu">filter</span>(smoking_status <span class="sc">==</span> <span class="st">&quot;never smoked&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb243-3"><a href="day-2.html#cb243-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>avg_glucose_level, <span class="at">y=</span>bmi)) <span class="sc">+</span></span>
<span id="cb243-4"><a href="day-2.html#cb243-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb243-5"><a href="day-2.html#cb243-5" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;never smoked&quot;</span>) <span class="sc">+</span></span>
<span id="cb243-6"><a href="day-2.html#cb243-6" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p>If we wanted to save a pdf of every category of <code>smoking_status</code>, we can convert our code into a loop. When working on a larger section of code, it is helpful to sketch out the steps you need to do with <code>#</code> comments to keep you focused.</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="day-2.html#cb244-1" tabindex="-1"></a>smoke_cat <span class="ot">&lt;-</span> <span class="fu">levels</span>(heart<span class="sc">$</span>smoking_status)</span>
<span id="cb244-2"><a href="day-2.html#cb244-2" tabindex="-1"></a>smoke_cat</span></code></pre></div>
<pre><code>## [1] &quot;formerly smoked&quot; &quot;never smoked&quot;    &quot;smokes&quot;</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="day-2.html#cb246-1" tabindex="-1"></a><span class="fu">getwd</span>() <span class="co"># get working directory</span></span></code></pre></div>
<pre><code>## [1] &quot;/Users/clin/Documents/CBWGitHub/INR-2024&quot;</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="day-2.html#cb248-1" tabindex="-1"></a><span class="cf">for</span>(cat <span class="cf">in</span> smoke_cat) {</span>
<span id="cb248-2"><a href="day-2.html#cb248-2" tabindex="-1"></a>  </span>
<span id="cb248-3"><a href="day-2.html#cb248-3" tabindex="-1"></a>  <span class="co"># Specify file name</span></span>
<span id="cb248-4"><a href="day-2.html#cb248-4" tabindex="-1"></a>  filename_cat <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;bmi_glucose_&quot;</span>, cat, <span class="st">&quot;.png&quot;</span>)</span>
<span id="cb248-5"><a href="day-2.html#cb248-5" tabindex="-1"></a>  <span class="fu">print</span>(filename_cat)</span>
<span id="cb248-6"><a href="day-2.html#cb248-6" tabindex="-1"></a>  </span>
<span id="cb248-7"><a href="day-2.html#cb248-7" tabindex="-1"></a>  <span class="co"># Making plot (based on code from above)</span></span>
<span id="cb248-8"><a href="day-2.html#cb248-8" tabindex="-1"></a>  </span>
<span id="cb248-9"><a href="day-2.html#cb248-9" tabindex="-1"></a>  plot_cat <span class="ot">&lt;-</span> heart <span class="sc">%&gt;%</span> <span class="co"># SAVE OUTPUT TO OBJECT</span></span>
<span id="cb248-10"><a href="day-2.html#cb248-10" tabindex="-1"></a>  <span class="fu">filter</span>(smoking_status <span class="sc">==</span> cat) <span class="sc">%&gt;%</span> <span class="co"># CHANGE TO cat</span></span>
<span id="cb248-11"><a href="day-2.html#cb248-11" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>avg_glucose_level, <span class="at">y=</span>bmi)) <span class="sc">+</span></span>
<span id="cb248-12"><a href="day-2.html#cb248-12" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb248-13"><a href="day-2.html#cb248-13" tabindex="-1"></a>  <span class="fu">ggtitle</span>(cat) <span class="sc">+</span> <span class="co"># CHANGE TO cat</span></span>
<span id="cb248-14"><a href="day-2.html#cb248-14" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb248-15"><a href="day-2.html#cb248-15" tabindex="-1"></a>  </span>
<span id="cb248-16"><a href="day-2.html#cb248-16" tabindex="-1"></a>  <span class="co">#print(plot_cat) # PRINT OUT PLOT</span></span>
<span id="cb248-17"><a href="day-2.html#cb248-17" tabindex="-1"></a>  </span>
<span id="cb248-18"><a href="day-2.html#cb248-18" tabindex="-1"></a>  <span class="co"># Saving the plot to file </span></span>
<span id="cb248-19"><a href="day-2.html#cb248-19" tabindex="-1"></a>  <span class="fu">png</span>(filename_cat, <span class="at">width =</span> <span class="dv">700</span>, <span class="at">height=</span> <span class="dv">500</span>, <span class="at">res=</span><span class="dv">120</span>) <span class="co"># Start saving whatever I make now to this file </span></span>
<span id="cb248-20"><a href="day-2.html#cb248-20" tabindex="-1"></a>  <span class="fu">print</span>(plot_cat)</span>
<span id="cb248-21"><a href="day-2.html#cb248-21" tabindex="-1"></a>  <span class="fu">dev.off</span>() <span class="co"># Stop saving</span></span>
<span id="cb248-22"><a href="day-2.html#cb248-22" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;bmi_glucose_formerly smoked.png&quot;</code></pre>
<pre><code>## [1] &quot;bmi_glucose_never smoked.png&quot;</code></pre>
<pre><code>## [1] &quot;bmi_glucose_smokes.png&quot;</code></pre>
</div>
<div id="exercise-7" class="section level3 hasAnchor">
<h3>Exercise<a href="day-2.html#exercise-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Copy and paste the loop from above and modify it so that the range of values on the x and y axis are the same for all plots.</p>
<div class="callout-orange">
<span class="callout-icon"><i class="fas fa-fire" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Tip</p>
</div>
<p>The limits of the x axis can be specified by adding a layer called <code>xlim(lower, upper)</code> where it takes two numbers - the lower limit followed by the upper limit. These numbers can be stored in objects or inputted directly . Similarly, there is a parallel function called <code>ylim()</code> which also takes the same two parameters</p>
</div>
</div>
<p>When working through the code, you can temporarily remove the code removing the axis labels by commenting out the lines with a hashtag.</p>
<p>Great! Now the y-axis does not change between the plots and they are directly comparable.</p>
</div>
<div id="conditional-for-loops" class="section level3 hasAnchor">
<h3>Conditional for Loops<a href="day-2.html#conditional-for-loops" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Boolean statements can be used to write conditional statements. If we do not want the loop to be applied to every item, we can add a condition.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="day-2.html#cb252-1" tabindex="-1"></a>food <span class="ot">&lt;-</span> <span class="st">&quot;pineapple&quot;</span></span>
<span id="cb252-2"><a href="day-2.html#cb252-2" tabindex="-1"></a></span>
<span id="cb252-3"><a href="day-2.html#cb252-3" tabindex="-1"></a><span class="cf">if</span>(food <span class="sc">==</span> <span class="st">&quot;pineapple&quot;</span>) {</span>
<span id="cb252-4"><a href="day-2.html#cb252-4" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;This indeed is a pineapple.&quot;</span>)</span>
<span id="cb252-5"><a href="day-2.html#cb252-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;This indeed is a pineapple.&quot;</code></pre>
<p>This will only output if the condition is met. We can also modify this statement to do something in case the condition is not met.</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="day-2.html#cb254-1" tabindex="-1"></a>food <span class="ot">&lt;-</span> <span class="st">&quot;orange&quot;</span></span>
<span id="cb254-2"><a href="day-2.html#cb254-2" tabindex="-1"></a></span>
<span id="cb254-3"><a href="day-2.html#cb254-3" tabindex="-1"></a><span class="cf">if</span>(food <span class="sc">==</span> <span class="st">&quot;pineapple&quot;</span>) {</span>
<span id="cb254-4"><a href="day-2.html#cb254-4" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;This indeed is a pineapple.&quot;</span>)</span>
<span id="cb254-5"><a href="day-2.html#cb254-5" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb254-6"><a href="day-2.html#cb254-6" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;This is NOT a pineapple.&quot;</span>)</span>
<span id="cb254-7"><a href="day-2.html#cb254-7" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;This is NOT a pineapple.&quot;</code></pre>
<p>Using <code>if else</code> statements will allow more customizability in our code. Let’s use this to add a new column called <code>ever_smoked</code> based on the value in the <code>smoking_status</code> column.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="day-2.html#cb256-1" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>stroke)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 3363  202</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="day-2.html#cb258-1" tabindex="-1"></a>heart<span class="sc">$</span>stroke_history <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb258-2"><a href="day-2.html#cb258-2" tabindex="-1"></a><span class="fu">head</span>(heart)</span></code></pre></div>
<pre><code>##      id gender age hypertension heart_disease ever_married     work_type
## 1  9046   Male  67            0             1          Yes       Private
## 2 51676 Female  61            0             0          Yes Self-employed
## 3 31112   Male  80            0             1          Yes       Private
## 4 60182 Female  49            0             0          Yes       Private
## 5  1665 Female  79            1             0          Yes Self-employed
## 6 56669   Male  81            0             0          Yes       Private
##   Residence_type avg_glucose_level bmi  smoking_status stroke stroke_history
## 1          Urban            228.69 240 formerly smoked      1             NA
## 2          Rural            202.21 419    never smoked      1             NA
## 3          Rural            105.92 199    never smoked      1             NA
## 4          Urban            171.23 218          smokes      1             NA
## 5          Rural            174.12 114    never smoked      1             NA
## 6          Urban            186.21 164 formerly smoked      1             NA</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="day-2.html#cb260-1" tabindex="-1"></a><span class="cf">for</span>(row <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(heart)) {</span>
<span id="cb260-2"><a href="day-2.html#cb260-2" tabindex="-1"></a>  <span class="cf">if</span>(heart<span class="sc">$</span>stroke[row] <span class="sc">==</span> <span class="st">&quot;1&quot;</span>) {</span>
<span id="cb260-3"><a href="day-2.html#cb260-3" tabindex="-1"></a>    heart<span class="sc">$</span>stroke_history[row] <span class="ot">&lt;-</span> <span class="st">&quot;confirmed_stroke&quot;</span></span>
<span id="cb260-4"><a href="day-2.html#cb260-4" tabindex="-1"></a>  } <span class="cf">else</span> { </span>
<span id="cb260-5"><a href="day-2.html#cb260-5" tabindex="-1"></a>    heart<span class="sc">$</span>stroke_history[row] <span class="ot">&lt;-</span> <span class="st">&quot;no_history&quot;</span></span>
<span id="cb260-6"><a href="day-2.html#cb260-6" tabindex="-1"></a>    }</span>
<span id="cb260-7"><a href="day-2.html#cb260-7" tabindex="-1"></a>  <span class="co"># else &gt;&gt; &quot;no_history&quot; </span></span>
<span id="cb260-8"><a href="day-2.html#cb260-8" tabindex="-1"></a>  </span>
<span id="cb260-9"><a href="day-2.html#cb260-9" tabindex="-1"></a>}</span>
<span id="cb260-10"><a href="day-2.html#cb260-10" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>stroke, heart<span class="sc">$</span>stroke_history)</span></code></pre></div>
<pre><code>##    
##     confirmed_stroke no_history
##   0                0       3363
##   1              202          0</code></pre>
</div>
<div id="exercise-8" class="section level3 hasAnchor">
<h3>Exercise<a href="day-2.html#exercise-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Expected fasting blood glucose concentrations defined by the WHO are between 70 - 100 mg/dL. Create a new column called <code>glucose_WHO</code> in which:</p>
<ul>
<li><code>avg_glucose_levels</code> less than 70 are annotated as <code>followup</code></li>
<li><code>avg_glucose_levels</code> between 70-100 are annotated as <code>average</code></li>
<li><code>avg_glucose_levels</code> over 100 are annotated as <code>followup</code></li>
</ul>
<div class="callout-orange">
<span class="callout-icon"><i class="fas fa-fire" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Tip</p>
</div>
<p>Conditions can be combined using the <code>&amp;</code> for <code>and</code> where as <code>|</code> is used for <code>or</code> statements.</p>
</div>
</div>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="day-2.html#cb262-1" tabindex="-1"></a><span class="fu">colnames</span>(heart) <span class="co"># SHOULD BE &#39;avg_glucose_level&#39; WITHOUT THE S AT THE </span><span class="re">END</span><span class="co"> </span></span></code></pre></div>
<pre><code>##  [1] &quot;id&quot;                &quot;gender&quot;            &quot;age&quot;              
##  [4] &quot;hypertension&quot;      &quot;heart_disease&quot;     &quot;ever_married&quot;     
##  [7] &quot;work_type&quot;         &quot;Residence_type&quot;    &quot;avg_glucose_level&quot;
## [10] &quot;bmi&quot;               &quot;smoking_status&quot;    &quot;stroke&quot;           
## [13] &quot;stroke_history&quot;</code></pre>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="day-2.html#cb264-1" tabindex="-1"></a><span class="co"># Sorry! </span></span>
<span id="cb264-2"><a href="day-2.html#cb264-2" tabindex="-1"></a></span>
<span id="cb264-3"><a href="day-2.html#cb264-3" tabindex="-1"></a>heart<span class="sc">$</span>glucose_WHO <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb264-4"><a href="day-2.html#cb264-4" tabindex="-1"></a></span>
<span id="cb264-5"><a href="day-2.html#cb264-5" tabindex="-1"></a><span class="cf">for</span>(row <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(heart)) { </span>
<span id="cb264-6"><a href="day-2.html#cb264-6" tabindex="-1"></a>  <span class="cf">if</span>(heart<span class="sc">$</span>avg_glucose_level[row] <span class="sc">&gt;</span> <span class="dv">70</span> <span class="sc">&amp;</span> heart<span class="sc">$</span>avg_glucose_level[row] <span class="sc">&lt;</span> <span class="dv">100</span>) {</span>
<span id="cb264-7"><a href="day-2.html#cb264-7" tabindex="-1"></a>  heart<span class="sc">$</span>glucose_WHO[row] <span class="ot">&lt;-</span> <span class="st">&quot;average&quot;</span></span>
<span id="cb264-8"><a href="day-2.html#cb264-8" tabindex="-1"></a>  } <span class="cf">else</span> { </span>
<span id="cb264-9"><a href="day-2.html#cb264-9" tabindex="-1"></a>    heart<span class="sc">$</span>glucose_WHO[row] <span class="ot">&lt;-</span> <span class="st">&quot;followup&quot;</span>}</span>
<span id="cb264-10"><a href="day-2.html#cb264-10" tabindex="-1"></a>}</span>
<span id="cb264-11"><a href="day-2.html#cb264-11" tabindex="-1"></a></span>
<span id="cb264-12"><a href="day-2.html#cb264-12" tabindex="-1"></a><span class="fu">table</span>(heart<span class="sc">$</span>glucose_WHO)</span></code></pre></div>
<pre><code>## 
##  average followup 
##     1610     1955</code></pre>
</div>
<div id="countinous-variables" class="section level3 hasAnchor">
<h3>Countinous Variables<a href="day-2.html#countinous-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the heart dataset, we have three continuous variables. In R, continuous variables will be <code>numeric</code> values. Continuous variable have a wide range of ordered values. For example, the <code>age</code> values have a range of 10 to 82 - any value in between is possible.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="day-2.html#cb266-1" tabindex="-1"></a><span class="co">#heart$bmi &lt;- as.numeric(heart$bmi)</span></span>
<span id="cb266-2"><a href="day-2.html#cb266-2" tabindex="-1"></a></span>
<span id="cb266-3"><a href="day-2.html#cb266-3" tabindex="-1"></a><span class="fu">ggplot</span>(heart, <span class="fu">aes</span>(<span class="at">x=</span>bmi)) <span class="sc">+</span> </span>
<span id="cb266-4"><a href="day-2.html#cb266-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-95-1.png" width="672" /></p>
<p>Staticians commonly prefer working with normally distributed data because this is a heavily studied and predictable distribution. Confirming that the variable is normally distributed opens up options for robust statistical approaches to be applied.</p>
<p>Is this heart dataset normally distributed?</p>
<p>QQ plots, or quantile-quantile plots, are unique scatterplots that help us determine the distribution. Rather than black and white diagnostic tool, this is a visualization tool for inform our analysis. The <code>qqnorm()</code> sorts the values in the vector and compares it to a theoretical normal distribution (the <code>norm</code> part of <code>qqnorm</code>).</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="day-2.html#cb268-1" tabindex="-1"></a><span class="fu">qqnorm</span>(heart<span class="sc">$</span>bmi)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<p>For a normal distribution, we ideally want a straight diagonal line. Notice the slight curve on the right end, we can see the tail is also on the right side of this histogram. Curves indicate deviation away from normality. This looks faily normal, we can check to see if a transformation improves the distribution.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="day-2.html#cb269-1" tabindex="-1"></a><span class="fu">ggplot</span>(heart, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log2</span>(bmi))) <span class="sc">+</span> </span>
<span id="cb269-2"><a href="day-2.html#cb269-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="day-2.html#cb271-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">log2</span>(heart<span class="sc">$</span>bmi))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-97-2.png" width="672" /></p>
<p>The tail is exaggerated. Since all transformations add some artificial noise, we avoid applying them when it does not significantly improve the shape of our data.</p>
<p>We will proceed with the non-transformed data.</p>
</div>
<div id="linear-models" class="section level3 hasAnchor">
<h3>Linear Models<a href="day-2.html#linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Linear regression models allow us to investigate the relationship between two continuous variables. For simple linear models, we have one independent and one dependent variable. The independent variable is the one that is being controlled or manipulated in the experiment, and the dependent variable will change respectively.</p>
<p>For example, if we are investigating if a high fat diet affects sleep quality, the diet is the independent variable (changing or is different between participants) while the sleep quality is the dependent variable (depending on the diet, the sleep quality will change).</p>
<p>Here, we are investigating the relation between bmi and avg_glucose_level</p>
<p>We’ll first visualize the two variables</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="day-2.html#cb272-1" tabindex="-1"></a><span class="fu">ggplot</span>(heart)<span class="sc">+</span></span>
<span id="cb272-2"><a href="day-2.html#cb272-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>bmi, <span class="at">y=</span>avg_glucose_level, <span class="at">alpha=</span><span class="fl">0.3</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
<p>Notice here the aes is specified in the <code>geom_point()</code> call rather than the parent <code>ggplot()</code> call. This is helpful if your plots have multiple layers and you want the aes to apply only to one layer. Parameters in the <code>ggplot()</code> call will apply to all layers in the plot where as parameters specified in the <code>geom_point()</code> will only affect this specific layer.</p>
<p>For this plot with only one layer, this has no functional impact on the plot made, but this will be important if you make more complex and layered plots.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="day-2.html#cb273-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_glucose_level <span class="sc">~</span> bmi, <span class="at">data =</span> heart)</span></code></pre></div>
<p>This can be read as <code>avg_glucose_level</code> as a function of <code>bmi</code></p>
<p>Use the function summary() on fit1 object to obtain more details of the model.</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="day-2.html#cb274-1" tabindex="-1"></a>summary</span></code></pre></div>
<pre><code>## function (object, ...) 
## UseMethod(&quot;summary&quot;)
## &lt;bytecode: 0x1087a1878&gt;
## &lt;environment: namespace:base&gt;</code></pre>
<p>This overall looks like a good model. The p-value is very low and statistically significant. However, the Multiple R-squared values is small and the slope of bmi is low.</p>
<p>From the results, we could conclude that changes in bmi are associated to the average glucose level as the p-value is less than 0.05. We can also state that as bmi increases, there will be an increase in the average glucose level as the slope is weakly positive 0.11.</p>
<p>Now that our model has given us the intercept and slope, we can use this information to build a formula in the format of</p>
<blockquote>
<p>dependent = (m)(independent) + b</p>
</blockquote>
<blockquote>
<p>avg_glucose_level = (0.097800)(bmi) + 90.823324</p>
</blockquote>
<p>We can use our knowledge of writing functions to calculate the predict the glucose level from the patient’s bmi</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="day-2.html#cb276-1" tabindex="-1"></a>calc_gluc <span class="ot">&lt;-</span> <span class="cf">function</span>(bmi_value) {</span>
<span id="cb276-2"><a href="day-2.html#cb276-2" tabindex="-1"></a>  (<span class="fl">0.097800</span><span class="sc">*</span>bmi_value) <span class="sc">+</span> <span class="fl">90.823324</span> <span class="co"># Change from brackets to * for multiply, bmi to bmi_value</span></span>
<span id="cb276-3"><a href="day-2.html#cb276-3" tabindex="-1"></a>}</span>
<span id="cb276-4"><a href="day-2.html#cb276-4" tabindex="-1"></a></span>
<span id="cb276-5"><a href="day-2.html#cb276-5" tabindex="-1"></a>heart[<span class="dv">3</span>, <span class="fu">c</span>(<span class="st">&quot;bmi&quot;</span>, <span class="st">&quot;avg_glucose_level&quot;</span>)]</span></code></pre></div>
<pre><code>##   bmi avg_glucose_level
## 3 199            105.92</code></pre>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="day-2.html#cb278-1" tabindex="-1"></a><span class="fu">calc_gluc</span>(<span class="dv">119</span>)</span></code></pre></div>
<pre><code>## [1] 102.4615</code></pre>
<p>Next, let’s visualize this using ggplot</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="day-2.html#cb280-1" tabindex="-1"></a><span class="co"># Start with code from previous point plot </span></span>
<span id="cb280-2"><a href="day-2.html#cb280-2" tabindex="-1"></a></span>
<span id="cb280-3"><a href="day-2.html#cb280-3" tabindex="-1"></a><span class="fu">ggplot</span>(heart, <span class="fu">aes</span>(<span class="at">x=</span>bmi, <span class="at">y=</span>avg_glucose_level, <span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">col =</span> stroke))<span class="sc">+</span></span>
<span id="cb280-4"><a href="day-2.html#cb280-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="co"># ADD PLUS SIGN</span></span>
<span id="cb280-5"><a href="day-2.html#cb280-5" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">90.823324</span>, <span class="at">slope =</span> <span class="fl">0.097800</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="co"># ADD THIS LINE</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
</div>
<div id="exercise-9" class="section level3 hasAnchor">
<h3>Exercise<a href="day-2.html#exercise-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hmm, this looks like there are two densities of data in this image. Let’s try to investigate if we can figure it out.</p>
<p>I’ve started you off by creating two new objects, an object called <code>heart_stroke</code> that contains only patents who experienced a stroke (stroke == 1) and a second object called <code>heart_nostroke</code> that contains only patents who have not experienced a stroke (stroke == 0).</p>
<p>Next, create two separate linear models called <code>fit_stroke</code> and <code>fit_nostroke</code> - are they different? How will you visualize the data?</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="day-2.html#cb281-1" tabindex="-1"></a>heart_stroke <span class="ot">&lt;-</span> <span class="fu">filter</span>(heart, stroke <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb281-2"><a href="day-2.html#cb281-2" tabindex="-1"></a><span class="fu">table</span>(heart_stroke<span class="sc">$</span>stroke)</span></code></pre></div>
<pre><code>## 
##   0   1 
##   0 202</code></pre>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="day-2.html#cb283-1" tabindex="-1"></a>heart_nostroke <span class="ot">&lt;-</span> <span class="fu">filter</span>(heart, stroke <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb283-2"><a href="day-2.html#cb283-2" tabindex="-1"></a><span class="fu">table</span>(heart_nostroke<span class="sc">$</span>stroke)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 3363    0</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="day-2.html#cb285-1" tabindex="-1"></a><span class="co"># From above: </span></span>
<span id="cb285-2"><a href="day-2.html#cb285-2" tabindex="-1"></a><span class="co"># fit &lt;- lm(avg_glucose_level ~ bmi, data = heart)</span></span>
<span id="cb285-3"><a href="day-2.html#cb285-3" tabindex="-1"></a></span>
<span id="cb285-4"><a href="day-2.html#cb285-4" tabindex="-1"></a>fit_stroke <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_glucose_level <span class="sc">~</span> bmi, <span class="at">data =</span> heart_stroke)</span>
<span id="cb285-5"><a href="day-2.html#cb285-5" tabindex="-1"></a>fit_nostroke <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_glucose_level <span class="sc">~</span> bmi, <span class="at">data =</span> heart_nostroke)</span>
<span id="cb285-6"><a href="day-2.html#cb285-6" tabindex="-1"></a></span>
<span id="cb285-7"><a href="day-2.html#cb285-7" tabindex="-1"></a><span class="fu">summary</span>(fit_stroke)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = avg_glucose_level ~ bmi, data = heart_stroke)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -92.34 -51.38 -27.21  60.90 138.98 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 118.92281   10.59306  11.226   &lt;2e-16 ***
## bmi           0.07479    0.04670   1.602    0.111    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 62.75 on 200 degrees of freedom
## Multiple R-squared:  0.01266,    Adjusted R-squared:  0.007726 
## F-statistic: 2.565 on 1 and 200 DF,  p-value: 0.1108</code></pre>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="day-2.html#cb287-1" tabindex="-1"></a><span class="fu">summary</span>(fit_nostroke)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = avg_glucose_level ~ bmi, data = heart_nostroke)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -72.67 -30.43 -13.96  10.36 164.40 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 89.92299    1.96082  45.860   &lt;2e-16 ***
## bmi          0.09507    0.00972   9.781   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 46.2 on 3361 degrees of freedom
## Multiple R-squared:  0.02768,    Adjusted R-squared:  0.02739 
## F-statistic: 95.68 on 1 and 3361 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="day-2.html#cb289-1" tabindex="-1"></a>fit_nostroke<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)         bmi 
## 89.92298677  0.09507385</code></pre>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="day-2.html#cb291-1" tabindex="-1"></a><span class="fu">ggplot</span>(heart, <span class="fu">aes</span>(<span class="at">x=</span>bmi, <span class="at">y=</span>avg_glucose_level, <span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">col =</span> stroke))<span class="sc">+</span></span>
<span id="cb291-2"><a href="day-2.html#cb291-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="co"># ADD PLUS SIGN</span></span>
<span id="cb291-3"><a href="day-2.html#cb291-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">90.823324</span>, <span class="at">slope =</span> <span class="fl">0.097800</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span> </span>
<span id="cb291-4"><a href="day-2.html#cb291-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> fit_nostroke<span class="sc">$</span>coefficients[<span class="dv">1</span>], <span class="at">slope =</span> fit_nostroke<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb291-5"><a href="day-2.html#cb291-5" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">100</span>, <span class="dv">200</span>)<span class="sc">+</span> </span>
<span id="cb291-6"><a href="day-2.html#cb291-6" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">100</span>, <span class="dv">200</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 2951 rows containing missing values or values outside the scale
## range (`geom_point()`).</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-104-1.png" width="672" /></p>
</div>
<div id="demo-detour-to-function-for-lm-plots" class="section level3 hasAnchor">
<h3>Demo Detour to Function for lm Plots<a href="day-2.html#demo-detour-to-function-for-lm-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="day-2.html#cb293-1" tabindex="-1"></a><span class="co"># The variables </span></span>
<span id="cb293-2"><a href="day-2.html#cb293-2" tabindex="-1"></a>which_data <span class="ot">&lt;-</span> heart_stroke</span>
<span id="cb293-3"><a href="day-2.html#cb293-3" tabindex="-1"></a>variable_call <span class="ot">&lt;-</span> <span class="st">&quot;avg_glucose_level ~ bmi&quot;</span></span>
<span id="cb293-4"><a href="day-2.html#cb293-4" tabindex="-1"></a>custom_col <span class="ot">&lt;-</span> <span class="st">&quot;blue&quot;</span></span>
<span id="cb293-5"><a href="day-2.html#cb293-5" tabindex="-1"></a></span>
<span id="cb293-6"><a href="day-2.html#cb293-6" tabindex="-1"></a></span>
<span id="cb293-7"><a href="day-2.html#cb293-7" tabindex="-1"></a></span>
<span id="cb293-8"><a href="day-2.html#cb293-8" tabindex="-1"></a><span class="co"># The actual task </span></span>
<span id="cb293-9"><a href="day-2.html#cb293-9" tabindex="-1"></a></span>
<span id="cb293-10"><a href="day-2.html#cb293-10" tabindex="-1"></a>lm_gluc_bmi <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">which_data =</span> heart_stroke, <span class="at">variable_call =</span> <span class="st">&quot;avg_glucose_level ~ bmi&quot;</span>, <span class="at">custom_col =</span> <span class="st">&quot;blue&quot;</span>) {</span>
<span id="cb293-11"><a href="day-2.html#cb293-11" tabindex="-1"></a></span>
<span id="cb293-12"><a href="day-2.html#cb293-12" tabindex="-1"></a>  <span class="co"># Run liner model </span></span>
<span id="cb293-13"><a href="day-2.html#cb293-13" tabindex="-1"></a>  </span>
<span id="cb293-14"><a href="day-2.html#cb293-14" tabindex="-1"></a>  <span class="co"># Make plot</span></span>
<span id="cb293-15"><a href="day-2.html#cb293-15" tabindex="-1"></a></span>
<span id="cb293-16"><a href="day-2.html#cb293-16" tabindex="-1"></a>fit_stroke <span class="ot">&lt;-</span> <span class="fu">lm</span>(variable_call, <span class="at">data =</span> which_data)</span>
<span id="cb293-17"><a href="day-2.html#cb293-17" tabindex="-1"></a></span>
<span id="cb293-18"><a href="day-2.html#cb293-18" tabindex="-1"></a><span class="fu">ggplot</span>(heart, <span class="fu">aes</span>(<span class="at">x=</span>bmi, <span class="at">y=</span>avg_glucose_level, <span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">col =</span> stroke))<span class="sc">+</span></span>
<span id="cb293-19"><a href="day-2.html#cb293-19" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="co"># ADD PLUS SIGN</span></span>
<span id="cb293-20"><a href="day-2.html#cb293-20" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> fit_nostroke<span class="sc">$</span>coefficients[<span class="dv">1</span>], <span class="at">slope =</span> fit_nostroke<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="at">color =</span> custom_col)</span>
<span id="cb293-21"><a href="day-2.html#cb293-21" tabindex="-1"></a></span>
<span id="cb293-22"><a href="day-2.html#cb293-22" tabindex="-1"></a>}</span>
<span id="cb293-23"><a href="day-2.html#cb293-23" tabindex="-1"></a></span>
<span id="cb293-24"><a href="day-2.html#cb293-24" tabindex="-1"></a><span class="fu">lm_gluc_bmi</span>(<span class="at">custom_col =</span> <span class="st">&quot;green3&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
</div>
<div id="notes-on-data-types" class="section level3 hasAnchor">
<h3>Notes on Data Types<a href="day-2.html#notes-on-data-types" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Numeric
-dbl doublets, int integers</p>
<p>Character
-char or fact factor
- characters are independent words
- factors have relations between identical entries</p>
<p>-categorical
- require factor</p>
<p>Logical</p>
<blockquote>
<blockquote>
<p>Differences are apparent when using a summary call</p>
</blockquote>
</blockquote>
</div>
<div id="day-2-project" class="section level3 hasAnchor">
<h3>Day 2 Project<a href="day-2.html#day-2-project" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this mini guided project, we will be working with a dataset that contains the prices and other attributes of almost 54,000 diamonds and is publicly available at: <a href="https://www.kaggle.com/datasets/shivam2503/diamonds" class="uri">https://www.kaggle.com/datasets/shivam2503/diamonds</a></p>
<p>Here is some more information about each column:</p>
<p>price price in US dollars ($326–$18,823)
carat weight of the diamond (0.2–5.01)
cut quality of the cut (Fair, Good, Very Good, Premium, Ideal)
color diamond colour, from J (worst) to D (best)
clarity a measurement of how clear the diamond is (I1 (worst), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (best))
x length in mm (0–10.74)
y width in mm (0–58.9)
z depth in mm (0–31.8)
depth total depth percentage = z / mean(x, y) = 2 * z / (x + y) (43–79)
table width of top of diamond relative to widest point (43–95)</p>
<p>Insert a code chunk underneath each step to carry out the instruction.</p>
<ol style="list-style-type: decimal">
<li>Read in the “diamonds.csv” data into an object called data. Use the <code>strongAsFactors</code> parameter to automatically import the character values as a factor. Check the object you created by printing out the first 10 rows and applying the summary function.</li>
</ol>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="day-2.html#cb294-1" tabindex="-1"></a>diamonds <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;../INR-2024/datasets/diamonds.csv&quot;</span>, <span class="at">header =</span> T, <span class="at">stringsAsFactors =</span> T)</span>
<span id="cb294-2"><a href="day-2.html#cb294-2" tabindex="-1"></a></span>
<span id="cb294-3"><a href="day-2.html#cb294-3" tabindex="-1"></a><span class="fu">head</span>(diamonds)</span></code></pre></div>
<pre><code>##   X carat       cut color clarity depth table price    x    y    z
## 1 1  0.23     Ideal     E     SI2  61.5    55   326 3.95 3.98 2.43
## 2 2  0.21   Premium     E     SI1  59.8    61   326 3.89 3.84 2.31
## 3 3  0.23      Good     E     VS1  56.9    65   327 4.05 4.07 2.31
## 4 4  0.29   Premium     I     VS2  62.4    58   334 4.20 4.23 2.63
## 5 5  0.31      Good     J     SI2  63.3    58   335 4.34 4.35 2.75
## 6 6  0.24 Very Good     J    VVS2  62.8    57   336 3.94 3.96 2.48</code></pre>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="day-2.html#cb296-1" tabindex="-1"></a><span class="fu">summary</span>(diamonds)</span></code></pre></div>
<pre><code>##        X             carat               cut        color        clarity     
##  Min.   :    1   Min.   :0.2000   Fair     : 1610   D: 6775   SI1    :13065  
##  1st Qu.:13486   1st Qu.:0.4000   Good     : 4906   E: 9797   VS2    :12258  
##  Median :26970   Median :0.7000   Ideal    :21551   F: 9542   SI2    : 9194  
##  Mean   :26970   Mean   :0.7979   Premium  :13791   G:11292   VS1    : 8171  
##  3rd Qu.:40455   3rd Qu.:1.0400   Very Good:12082   H: 8304   VVS2   : 5066  
##  Max.   :53940   Max.   :5.0100                     I: 5422   VVS1   : 3655  
##                                                     J: 2808   (Other): 2531  
##      depth           table           price             x         
##  Min.   :43.00   Min.   :43.00   Min.   :  326   Min.   : 0.000  
##  1st Qu.:61.00   1st Qu.:56.00   1st Qu.:  950   1st Qu.: 4.710  
##  Median :61.80   Median :57.00   Median : 2401   Median : 5.700  
##  Mean   :61.75   Mean   :57.46   Mean   : 3933   Mean   : 5.731  
##  3rd Qu.:62.50   3rd Qu.:59.00   3rd Qu.: 5324   3rd Qu.: 6.540  
##  Max.   :79.00   Max.   :95.00   Max.   :18823   Max.   :10.740  
##                                                                  
##        y                z         
##  Min.   : 0.000   Min.   : 0.000  
##  1st Qu.: 4.720   1st Qu.: 2.910  
##  Median : 5.710   Median : 3.530  
##  Mean   : 5.735   Mean   : 3.539  
##  3rd Qu.: 6.540   3rd Qu.: 4.040  
##  Max.   :58.900   Max.   :31.800  
## </code></pre>
<ol start="2" style="list-style-type: decimal">
<li>We’ll start investigating the relationship between different variables with price. Create a boxplot using ggplot with the cut on the x axis and the price on the y axis.</li>
</ol>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="day-2.html#cb298-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> diamonds, <span class="fu">aes</span>(<span class="at">x =</span> cut, <span class="at">y =</span> price)) <span class="sc">+</span> </span>
<span id="cb298-2"><a href="day-2.html#cb298-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<ol start="3" style="list-style-type: decimal">
<li>Using the code in the previous step as foundation, create an object called <code>diamonds_categorical</code> that contains the name of all the categorical columns. Then, write a loop to print out a separate plot with each of the different categorical variables on the x axis and price on the y-axis.</li>
</ol>
<div class="callout-orange">
<span class="callout-icon"><i class="fas fa-fire" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Tip</p>
</div>
<p>Remember how aes can be specified in both the <code>ggplot()</code> or <code>geom_xx()</code> layer? You will need to use this because we are string the name of a column as a variable in our loop and in order for R to know that it is looking for a column name rather than an object, you will need to use the <code>aes_string()</code> parameter for just the <code>geom_boxplot()</code> layer to specify the changing x axis. The y axis can remain with <code>aes()</code> in the parent <code>ggplot()</code> layer.</p>
</div>
</div>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="day-2.html#cb299-1" tabindex="-1"></a><span class="fu">str</span>(diamonds)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    53940 obs. of  11 variables:
##  $ X      : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ carat  : num  0.23 0.21 0.23 0.29 0.31 0.24 0.24 0.26 0.22 0.23 ...
##  $ cut    : Factor w/ 5 levels &quot;Fair&quot;,&quot;Good&quot;,..: 3 4 2 4 2 5 5 5 1 5 ...
##  $ color  : Factor w/ 7 levels &quot;D&quot;,&quot;E&quot;,&quot;F&quot;,&quot;G&quot;,..: 2 2 2 6 7 7 6 5 2 5 ...
##  $ clarity: Factor w/ 8 levels &quot;I1&quot;,&quot;IF&quot;,&quot;SI1&quot;,..: 4 3 5 6 4 8 7 3 6 5 ...
##  $ depth  : num  61.5 59.8 56.9 62.4 63.3 62.8 62.3 61.9 65.1 59.4 ...
##  $ table  : num  55 61 65 58 58 57 57 55 61 61 ...
##  $ price  : int  326 326 327 334 335 336 336 337 337 338 ...
##  $ x      : num  3.95 3.89 4.05 4.2 4.34 3.94 3.95 4.07 3.87 4 ...
##  $ y      : num  3.98 3.84 4.07 4.23 4.35 3.96 3.98 4.11 3.78 4.05 ...
##  $ z      : num  2.43 2.31 2.31 2.63 2.75 2.48 2.47 2.53 2.49 2.39 ...</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="day-2.html#cb301-1" tabindex="-1"></a>diamonds_categorical <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;cut&quot;</span>, <span class="st">&quot;color&quot;</span>, <span class="st">&quot;clarity&quot;</span>)</span>
<span id="cb301-2"><a href="day-2.html#cb301-2" tabindex="-1"></a></span>
<span id="cb301-3"><a href="day-2.html#cb301-3" tabindex="-1"></a><span class="cf">for</span>(cat <span class="cf">in</span> diamonds_categorical) {</span>
<span id="cb301-4"><a href="day-2.html#cb301-4" tabindex="-1"></a>  diaplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> diamonds, <span class="fu">aes</span>(<span class="at">y =</span> price)) <span class="sc">+</span> </span>
<span id="cb301-5"><a href="day-2.html#cb301-5" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="fu">aes_string</span>(<span class="at">x =</span> cat))</span>
<span id="cb301-6"><a href="day-2.html#cb301-6" tabindex="-1"></a>  </span>
<span id="cb301-7"><a href="day-2.html#cb301-7" tabindex="-1"></a>  <span class="fu">print</span>(diaplot)</span>
<span id="cb301-8"><a href="day-2.html#cb301-8" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
## ℹ Please use tidy evaluation idioms with `aes()`.
## ℹ See also `vignette(&quot;ggplot2-in-packages&quot;)` for more information.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning
## was generated.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-108-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-108-2.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-108-3.png" width="672" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Write a function called <code>diamond_continous</code> that allows you to make a scatterplot that accepts one variable to plot on the x-axis as well as another variable to color the plot by as the inputs. Price will remain on the y-axis.</li>
</ol>
<div class="callout-orange">
<span class="callout-icon"><i class="fas fa-fire" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Tip</p>
</div>
<p>Start out by making one plot, make it generalized, and then convert this into a function.</p>
</div>
</div>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="day-2.html#cb303-1" tabindex="-1"></a>diamond_continous <span class="ot">&lt;-</span> <span class="cf">function</span>(contV, colV) {</span>
<span id="cb303-2"><a href="day-2.html#cb303-2" tabindex="-1"></a>  </span>
<span id="cb303-3"><a href="day-2.html#cb303-3" tabindex="-1"></a>  diaPlot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> diamonds, <span class="fu">aes</span>(<span class="at">y =</span> price)) <span class="sc">+</span> </span>
<span id="cb303-4"><a href="day-2.html#cb303-4" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes_string</span>(<span class="at">x =</span> contV, <span class="at">color =</span> colV), <span class="at">alpha =</span> <span class="fl">0.4</span>)</span>
<span id="cb303-5"><a href="day-2.html#cb303-5" tabindex="-1"></a>  </span>
<span id="cb303-6"><a href="day-2.html#cb303-6" tabindex="-1"></a>  <span class="fu">print</span>(diaPlot)</span>
<span id="cb303-7"><a href="day-2.html#cb303-7" tabindex="-1"></a>  </span>
<span id="cb303-8"><a href="day-2.html#cb303-8" tabindex="-1"></a>}</span>
<span id="cb303-9"><a href="day-2.html#cb303-9" tabindex="-1"></a></span>
<span id="cb303-10"><a href="day-2.html#cb303-10" tabindex="-1"></a><span class="fu">diamond_continous</span>(<span class="st">&quot;carat&quot;</span>, <span class="st">&quot;clarity&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-109-1.png" width="672" /></p>
<ol start="5" style="list-style-type: decimal">
<li>Based on your plots from the previous step, pick a continuous variable to compare with price and create a linear model. Make sure the price is the dependent variable. Add a layer to your plot generated by the function to include the equation of the line.</li>
</ol>
<p>Is the relationship significant?</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="day-2.html#cb304-1" tabindex="-1"></a>fit_diamond <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat, <span class="at">data =</span> diamonds)</span>
<span id="cb304-2"><a href="day-2.html#cb304-2" tabindex="-1"></a></span>
<span id="cb304-3"><a href="day-2.html#cb304-3" tabindex="-1"></a>fit_diamond<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)       carat 
##   -2256.361    7756.426</code></pre>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="day-2.html#cb306-1" tabindex="-1"></a><span class="fu">diamond_continous</span>(<span class="st">&quot;carat&quot;</span>, <span class="st">&quot;clarity&quot;</span>) <span class="sc">+</span> </span>
<span id="cb306-2"><a href="day-2.html#cb306-2" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> fit_diamond<span class="sc">$</span>coefficients[<span class="dv">1</span>], <span class="at">slope =</span> fit_diamond<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning
## was generated.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-110-2.png" width="672" /></p>
<div class="callout-green">
<span class="callout-icon"><i class="fas fa-circle-check" aria-hidden="true"></i></span>
<div class="callout-content">
<div class="callout-title-static" style="margin-bottom: 0.5em;">
<p>Lab Completed!</p>
</div>
<p>Congratulations! You have completed Lab 2!</p>
</div>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="day-1.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/bioinformaticsdotca/INR_2024/blob/main/020-module-2.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
